### ISSUE TITLE
プロキシのある環境でgit clone https が失敗する

### ISSUE THREAD

**Issue by Urada** [alminium/alminium#103]
プロキシのある環境でCentOS6を使用しています。
最新版のGitを yum localinstallでインストールして、Git clone  https://github.com/alminium.....
を実行すると下記のエラーが出ます。

Cloning into 'alminium' ...
数分後、下記のエラーあり
error: Empty reply from server while accessing https://github.com/alminium/alminium.git/info/refs
fatal : HTTP request failed

試しにGitのバージョンをCentOS6のyum installでインストールできる 1.7.1 にしてみたところ、git cloneができました。

最新版のGitでは何かの追加設定が必要でしょうか？
ちなみに、最新版Gitをインストールした後、http.sslVerify を false にしても解決できませんでした。

どなたかご教授の程よろしくお願い致します。

**Comment by Urada** [comment]
追加情報です。
最新版Gitで、下記のように変更すると問題なくgit cloneできます。
Git clone https://github.com/alminium.....
　　↓
Git clone http://github.com/alminium.....

ですが、その後のALMiniumインストールで https://からのインストールで行き詰ってしまうのです。
プロキシ設定はしています。

よろしくお願い致します。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

Gitのバージョンは何で、最新版のバージョンはどこから取ってきたでしょうか？

ALMiniumはCentOSにクリーンな環境からインストールすることを想定しています。
CentOSの標準のGit以外では動作検証をしていません。
どうしても利用したいのであれば、最新版のGitALMiniumをインストールした後でGitをバージョンアップ
してみてください。

よろしくお願いします。

**Comment by Urada** [comment]
下記のURLから1.7.11を取ってきてインストールしました。
http://pkgs.repoforge.org/git/

> 最新版のGitALMiniumをインストールした後でGitをバージョンアップしてみてください。

今のところはそうしていますが、何かプラグイン追加で、再度 git cloneをする必要が生じた時は
その都度Gitのバージョンを下げるのは辛いです。

他のユーザもCentOSの標準のGitで入れているのでしょうか？
もし解決方法を知っている方がいましたら是非教えてください。

**Comment by mikoto20000** [comment]
お返事がおそくなりすみません。

ALMiniumのインストーラでは、標準のGit以外での検証はしていません。
また、プラグインを追加する場合は、ALMiniumインストーラを利用しないので、
個別にgit clone http://...　を実行すればバージョンを下げる必要はないかと思います。

よろしくおねがいします。
