### ISSUE TITLE
./smelt でインストールするとgemのバージョンが古くて起動できません

### ISSUE THREAD

**Issue by tukiyo** [alminium/alminium#104]
http://qiita.com/tukiyo/items/53b2fd1c19b809c713f6

Ubuntu13.04x64とCentOS6.4x64両方でインストールを試したけどどちらも`rake-compiler`のインストールに失敗した。
ので、どこが駄目か調べてみました。

アンインストールは`sudo sh ./uninstall`

`gem -v`の結果が`1.8.23`だとインストール途中でエラーが表示されるので、`1.8.25`にあげる必要がある。

[rubygems-1.8.25.tgz](http://rubyforge.org/frs/?group_id=126)を解凍し`sudo ruby ./setup.rb`で1.8.25に上がります。

そこまで出来たら`sudo ./smelt`でインストール開始。

・・・

無事起動できました。

**Comment by mikoto20000** [comment]
コメントありがとうございます。

CentOSのデフォルトでは、ruby2.0/gem2.0がインストールされるので問題ないと思うのですが、
ひょっとして、ruby1.8をインストールしたのでしょうか？

また、Ubuntuではruby1.9.3がインストールされるので、同じく問題にならないと思うのですが、、

すいませんが、環境についてお聞かせ頂ければと思います。

よろしくお願いします。

**Comment by taksatou** [comment]
Ubuntu12.04 でも同様の現象に遭遇しました。

先程pull requestをさせて頂きましたが、 #106 のようにして回避できそうです。

**Comment by mikoto20000** [comment]
masterブランチへマージしたのでクローズします。

対応ありがとうございました。

**Comment by tukiyo** [comment]
対応有難うございました。OpenVZの13.04 32bitでもalminiumのインストール成功しました。
なお13.10ではインストールに失敗しましたがまたそれは別のお話・・・
