### ISSUE TITLE
Gitmikeテーマのバージョンアップ

### ISSUE THREAD

**Issue by soappp** [alminium/alminium#105]
ALMiniumのデフォルトテーマであるGitmikeですが、ALMiniumに同梱されているものは少々古いようです。
この影響で、Redmine 2.0以前のALMiniumのデータを引き継ぐ形で最新のALMiniumにバージョンアップを行うと、チケット一覧画面におけるチケットの色が、チケットの優先度と連動しなくなってしまいます。
同梱されているGitmikeを、以下から入手できる最新版をベースとしたものに差し替えていただければ、チケットの色に関する問題は解消すると考えています。
https://github.com/makotokw/redmine-theme-gitmike
### 回避方法

最新のGitmikeに手動で入れ替える。
### 補足

チケットの色がおかしくなる原因等につきましては、ALMiniumのバージョンアップ手順を紹介する下記ブログ記事の末尾に記載しておきました。よろしければご参照いただければ幸いです。
http://d.hatena.ne.jp/soappp/20130902/1378133950

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。コメントを受けdevブランチは修正していたのですが、
masterブランチへも反映しました。

今後ともよろしくおねがいいたしますm(__)m
