### ISSUE TITLE
インストール後のapache再起動でエラーが起きる

### ISSUE THREAD

**Issue by tombijp** [alminium/alminium#108]
CentOS 6.4 64bit版でローカルのPCにalminiumをインストールしたところ、
インストール最後のapache再起動時にWarningが記述され、ブラウザでホスト名にアクセスするとalminiumのTOPページが表示されない。

Warning内容：Warning: DocumentRoot [/opt/alminium/public] does not exist

インストール前にしたこととしては、
・/etc/sysconfig/iptablesに80ポートの許可を記述
・/etc/sysconfig/network-scripts/ifcfg-eth0のネットワーク設定を記述
・yum -y update
くらいです。

**Comment by tombijp** [comment]
再度CentOS6.4をクリーンインストールして、今度はyum update等せずにネットワーク設定のみ完了した状態で
説明にあったコマンドによりインストールをしましたが同じ結果となりました。
途中、Bundler::GemfileNotFoundrake aborted!No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)というメッセージが表示されたのですが、GemfileがないためにRedmineのインストールにこけているのかと想定しています。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。ちょっと、確認する時間が取れないのですが、バージョンはmasterのHEADをお使いでしょうか？あと、developブランチでも同じ結果となるでしょうか？

あと、上記のログは、一番最初に表示されたエラーメッセージでしょうか？（どこかでこけるとその後ディレクトリの移動に失敗し、連続してエラーとなったりしますので、、)

まずは、問題を切り分けれる情報を頂ければと思います。

よろしくお願い致します。

**Comment by tombijp** [comment]
ご連絡ありがとうございます。
取り急ぎ、インストールを行ったバージョンはmasterです。
git tag/git checkoutによる変更は行っておりません。
またdevelopブランチは試していませんので試してみたいと思います。

ログの件ですが/opt/alminium/...のところまでしか確認出来ていないです。
何ヶ所か同じエラーが出ていました。
但しインストール自体は最後まで進みます。

最後のhttpd restartのところで/etc/httpd/conf.d/redmine.confに記載
されているDocumentRootの/opt/alminium/publicがありません、ということでエラーになります。
（すいません。/root/install.logに残っているかと思ったら、インストールログが残っていませんでした。
　確認する箇所があればご指示いただければ確認させていただきます。）

**Comment by mikoto20000** [comment]
エラーが起こっても途中で止まるようになっていないため、最後まですすんでしまっています。

エラーは、コンソールから消えてしまっていると思いますが、何とか最初のエラーが分かれば良いのですが、、、

**Comment by tombijp** [comment]
今確認しましたが、devブランチでも同じエラーとなりました。
![alminium1](https://f.cloud.github.com/assets/5886424/1638979/1f1380f8-5817-11e3-965f-1f097bebe5a5.JPG)
最初のエラーメッセージの写真ですが、見れますでしょうか？

この後に何回かrake aborted! No Rakefile foundというエラーが出て、
もう一回エラーメッセージが出ました。

![alminium2](https://f.cloud.github.com/assets/5886424/1639010/aa800094-5817-11e3-896c-96cac3128639.JPG)

**Comment by akiko-pusu** [comment]
こんばんは。Vagrant + CentOS6.4 で動かす環境があったので、試してみました。

alminiumのmasrerを使ってみたのですが、
たぶん同じ所でエラーになっている感じです。

```
2013-11-28 10:55:13 (5.65 MB/s) - `redmine-2.3.1.tar.gz' saved [41/41]

HTTP request sent, awaiting response... 200 OK
Length: 41 [text/html]
Saving to: `redmine-2.3.1.tar.gz'

     0K                                                       100% 5.65M=0s

2013-11-28 10:55:13 (5.65 MB/s) - `redmine-2.3.1.tar.gz' saved [41/41]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat `cache/redmine-2.3.1/*': No such file or directory
cp: cannot create regular file `/opt/alminium/config/': Is a directory
cp: cannot create regular file `/opt/alminium/config/': Is a directory
cp: target `/opt/alminium/public/themes/' is not a directory
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

もう一回試してみますね。

**Comment by akiko-pusu** [comment]
もう一回試してみました。
wget してきたはずのredmine-2.3.1.tar.gz のサイズを見てみたところ、サイズが少ししかなかったので、
cat してみると、”RubyForge Could Not Connect to Database” というメッセージが書かれているだけでした。

正常なRedmineのソースのtgzではないようです。
今、どうやらRubyForge側の問題のような気がします。

[vagrant@centos-tare cache]$ pwd
/tmp/alminium/cache
[vagrant@centos-tare cache]$ cat redmine-2.3.1.tar.gz 
RubyForge Could Not Connect to Database: [vagrant@centos-tare cache]$

**Comment by tombijp** [comment]
追記ありがとうございます。
Rubyforge.orgにアクセスするとRubyForge Could Not Connect to Database:と表示されますね。

RubyForgeは廃止、RubyGems.orgへ
http://www.infoq.com/jp/news/2009/10/rubyforge-phased-out-rubygemsorg

この記事と関係はあるんでしょうか。

**Comment by akiko-pusu** [comment]
redmine.org のDownloadのページを見たら、注意書きが出てました。
- http://www.redmine.org/projects/redmine/wiki/Download

> Important note: Due to rubyforge.org being down, the 2.3.4 downloads are temporarily relocated to hz6.de since Nov 27, 2013. We hope to provide the files from redmine.org shortly.
> See the Changelog for details and RedmineInstall for installation instructions or RedmineUpgrade for upgrading instructions.
> Older releases can be found at Rubyforge.

最新版は http://redmine.hz6.de から取れるようですが、rubyforgeはまだダメっぽいですね。

**Comment by tombijp** [comment]
上記のhttp://www.redmine.org/projects/redmine/wiki/Download にRedmineの2.3.4版のダウンロードURLは
ありました。
　http://www.redmine.org/releases/redmine-2.3.4.tar.gz

結局のところwgetしてくる先がrubyforgeですからrubyforge待でしょうか。

**Comment by mikoto20000** [comment]
akiko-pusuさん、フォローありがとうございます。tombijp追加調査ありがとうございます。

ALMiniumのスクリプトsmeltの中にredmineのtar.gzのURLの記載があるので、その部分を修正すると動作すると思います。

＃ そして、できれば修正をdevelopブランチへプルリクエストいただけるとありがたいです(汗

**Comment by akiko-pusu** [comment]
もとの redmine-2.3.1 は、http://www.redmine.org/releases/　には無いので、redmine-2.3.4.tar.gz で取得する、という感じに変えてみますね。

**Comment by akidevolive** [comment]
同様の問題ではまったので、devブランチをclone、smeltに以下修正を入れてインストール完了。

RM_VER=2.3.4
RM_ARC=http://www.redmine.org/releases/redmine-2.3.4.tar.gz

http://localhost/でアクセスしたところ次のエラーがブラウザ上に出ました。

You specified: selenium-webdriver (= 2.35.1) and selenium-webdriver (>= 0)
 (Bundler::GemfileError)
  /opt/alminium/Gemfile:95:in `instance_eval&apos;
  (eval):7:in`block (2 levels) in eval_gemfile&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/dsl.rb:159:in `group&apos;
  (eval):1:in`block in eval_gemfile&apos;
  /opt/alminium/Gemfile:95:in `instance_eval&apos;
  /opt/alminium/Gemfile:95:in`block in eval_gemfile&apos;
  /opt/alminium/Gemfile:93:in `glob&apos;
  /opt/alminium/Gemfile:93:in`eval_gemfile&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/dsl.rb:30:in `instance_eval&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/dsl.rb:30:in`eval_gemfile&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/dsl.rb:9:in `evaluate&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:19:in`build&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:148:in `definition&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:116:in`setup&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>&apos;
  /usr/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in`require&apos;
  /usr/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `rescue in require&apos;
  /usr/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:124:in`require&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/lib/phusion_passenger/loader_shared_helpers.rb:219:in `block in run_load_path_setup_code&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/lib/phusion_passenger/loader_shared_helpers.rb:333:in`running_bundler&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/lib/phusion_passenger/loader_shared_helpers.rb:217:in `run_load_path_setup_code&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/helper-scripts/rack-preloader.rb:96:in`preload_app&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/helper-scripts/rack-preloader.rb:150:in `<module:App>&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/helper-scripts/rack-preloader.rb:29:in`module:PhusionPassenger&apos;
  /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.26/helper-scripts/rack-preloader.rb:28:in `<main>&apos;

**Comment by akiko-pusu** [comment]
Pull Request送ってみました。お作法がまた間違っていたら申し訳ありません…。

ただし、これだけだとダウンロードのエラーが出ないだけで、その後のApache2 + Passengerの起動で、 @akio-t さんと同じくエラーが出てしまいます。
色々試したところ、Redmine BacklogsのGemfileと、Redmine HudsonのGemfileとで、テスト用に指定しているselenium-webdriverやcucumberのバージョンが異なっているのが原因のようでした。

Redmine Hudsonはテスト用以外に指定しているgemが無かったので、プラグインのbundle install…の直前に、Gemfileをリネームして対比させると、なんとか上手くインストールと起動ができました。

良いやり方かどうかは分かりませんが、こんな処理で対応しています…。

https://github.com/akiko-pusu/alminium/commit/125dec40c6b2a9e38a3bc8a6098a59b2c88cef48

**Comment by mikoto20000** [comment]
akiko-pusuさんのプルリクエストをマージしました。

tombijp さん、 akio-t さん、よろしければdevブランチで試してみてください。

よろしくお願いします。

**Comment by tombijp** [comment]
mikoto20000さん、akiko-pusuさん、akio-tさん

取り急ぎdevブランチでインストール完了出来ましたのでご連絡させていただきます。
ご対応、ご尽力いただきましてありがとうございました。

**Comment by akidevolive** [comment]
mikoto20000さん、akiko-pusuさん

お忙しい中ご対応ありがとうございました。
devブランチでのインストール、及び起動までの確認無事成功しました。

但し、こちら設定だけになるのかなと思いますが以下のメッセージが
ブラウザ上に表示されます。

「バックログが設定されていません。設定画面 管理 > プラグイン, からリンク 設定 をクリックして設定してください。フィールドを設定後、このページへ戻りツールを利用してください。」

スレ違いな気もしますが、こちらの対応方法ご教授頂ければと思います。
よろしくお願いします。
