### ISSUE TITLE
coderayのインストールが出来ません・・・。

### ISSUE THREAD

**Issue by tukiyo** [alminium/alminium#112]
[coderay](http://coderay.rubychan.de)をインストールしたかったので

``` bash:
git clone git://github.com/rubychan/coderay.git
sudo mv coderay /opt/alminium/plugins/
```

としたのですが、coderayが 管理->プラグイン 一覧に表示されません。
なにか間違っていますでしょうか。
以下も試しましたがダメでした。

``` bash:
sudo mkdir -p /opt/alminium/vendor/plugins/
sudo mv coderay /opt/alminium/vendor/plugins/
```

**Comment by mikoto20000** [comment]
お返事がおそくなりすみません。

coderayは、標準で/opt/aliminium/vendor/bundler/ruby/2.0.0/gems の下に
インストールされていると思います。

インストールが失敗していないかどうか、インターネット接続の設定(特にプロキシ)
の設定が誤っていないかどうかまずはご確認ください。

**Comment by mikoto20000** [comment]
お返事がないようなので、クローズさせていただきます。
