### ISSUE TITLE
Ruby 2.1対応

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#114]
下記の　SPEC or RPM　を使わせてもらってやればいいでしょうか。

http://blog.hansode.org/archives/52637025.html

**Comment by akiko-pusu** [comment]
お手伝いできることがあれば、着手します！

**Comment by mikoto20000** [comment]
ありがとうございます^^

上記のSPECを利用して、Ruby2.1で動作できるようにしていただけるとありがたいです。
ruby2.1-rm2.4ブランチを作成しましたので、適当にコミットしてください。

できれば、ビルド済みのRPMを直接取得してインストールするようにしたいですが、raw
形式でリポジトリからの取得に失敗するようです。今まで通りSPECからビルドするのが
無難そうでしょうか。変更が必要そうなファイルは、
- inst-script/rhel6/ruby2.0-install
  - SPECのバージョン、tar,gzのバージョンを変更
- inst-script/rhel6/httpd-*
  - rubyのパスを変更

辺りだと思います(見落として他にもあるかもしれません)。passengerのruby2.1の対応状況が
分からならないので、ひょっとしたら動かない可能性があります。passengerのリポジトリを
見る限り、2.1用の特に修正は入ってないので、そのまま行ける可能性もあります。
- https://github.com/phusion/passenger/commits/master

取り急ぎ。

**Comment by akiko-pusu** [comment]
ruby2.1は上記の手順でインストールできました。
なお、2.1.0から上記のblogに記載のある通り、バージョンの方針が変わったようです。

多分、これがその件かと思います。
https://www.ruby-lang.org/ja/news/2013/12/21/semantic-versioning-after-2-1-0/

ただいま、rubyインストール後のapacheの起動でコケてしまっているので、なぜか確認中です。

**Comment by mikoto20000** [comment]
masterブランチへRuby2.1対応のコードをマージしました。対応ありがとうございました。
