### ISSUE TITLE
/etc/httpd/conf.d/subversion.conf も有効にするには？

### ISSUE THREAD

**Issue by kazuya2013** [alminium/alminium#115]
ALMiniumで使用するSubversionの設定は下記(1)の設定ファイルでしていると思いますが、別のシステム導入で、下記(2)の設定ファイルも有効にするにはどうしたら良いでしょうか？

(1) /etc/httpd/conf.d/vcs.conf
(2) /etc/httpd/conf.d/subversion.conf

**Comment by akiko-pusu** [comment]
/etc/httpd/httpd.conf がメインの設定ファイルで、その中に "Include conf.d/*.conf" という指定さえあれば、
/etc/httpd/conf.d/ 以下に置いてあるものが有効になるかと思います。
如何でしょう。

**Comment by mikoto20000** [comment]
akiko-pusuさんの記述通りですのクローズします。追加で問題があればreopenしてください。
