### ISSUE TITLE
サービス化したJenkinsがNullPointerExceptionで利用できない

### ISSUE THREAD

**Issue by akiko-pusu** [alminium/alminium#116]
Jenkinsのインストールを有効にしてセットアップしたところ、80番, 443番, 8080番での /jenkins でのアクセスともに、NullPointerExceptionで正しく利用できない状態になりました。

Jenkinsのサービスを停止して、コマンドラインでJenkinsを起動すると、問題なく利用できます。
エラーの再現性を確認したところ、ALMinium入りではなく素のJenkinsをインストールしてサービス化をした場合は、問題は発生しませんでした。

どうやらconfig.xmlの書き方に問題（セキュリティレルムの記載に変更）があったようです。
いったんconfig.xml 無しでJenkinsを起動し、設定画面からReverse Proxy Authを有効にした場合、下記のような設定になりましたので、こちらをjenkins-config.xml に仕込むといいのではないかと思っています。

```
  <securityRealm class="org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm" plugin="reverse-proxy-auth-plugin">
    <authContext/>
    <inhibitInferRootDN>false</inhibitInferRootDN>
    <userSearchBase></userSearchBase>
    <userSearch>uid={0}</userSearch>
    <forwardedUser>X-Forwarded-User</forwardedUser>
    <authorities/>
  </securityRealm>
```

**Comment by cyberblack28** [comment]
以下のページから、reverse-proxy-auth-pluginを1.3.1にするとjenkinsの管理コンソールが表示されなくなるようです。

http://jenkins-ci.361315.n4.nabble.com/JIRA-reverse-proxy-auth-JENKINS-21304-NPE-Reverse-Proxy-Authentication-td4686761.html

aluminiumでjenkinsをインストールする際に、reverse-proxy-auth-pluginが自動でインストールされるため、
インストール完了後にjenkinsの管理コンソールに接続するとエラーが出てしまうようです。

私が回避した方法は、「/var/lib/jenkins/plugins/」内にある以下のファイルを別のディレクトリに退避して、
jenkinsのサービスをrestartして、jenkinsの管理コンソールにアクセスすることで回避できました。

reverse-proxy-auth-plugin
reverse-proxy-auth-plugin.bak
reverse-proxy-auth-plugin.jpi

このプラグインのバグフィックスがいつになるかわかりませんが、
1.0.1であれば問題が出ていないようです。

**Comment by mikoto20000** [comment]
既に修正されているのでクローズします。
