### ISSUE TITLE
メモリが少ないマシン上でインストールに失敗する

### ISSUE THREAD

**Issue by yamagon** [alminium/alminium#119]
Ubuntu12.4.3を設定してalminiumをインストールしてみましたが
Index　of／の表示となりRedmineのTOP画面が表示されません。
特別な設定が必要なのでしょうか。

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。

最近のバージョンは、Ubuntuではあまりテストされていません。上記の症状は、Apacheの設定がうまく効いていないためと思われます。Apacheの設定にRailsの設定が追加されているかどうか確認してみてください。

解決できない場合は、CentOS6をご利用することをお勧めします。

**Comment by angelndxp** [comment]
Amazon Linux の最新版は、CentOS6x互換です。
AWSで使うなら、そちらを使うとよいと思います。

**Comment by yamagon** [comment]
ご回答有難う御座います。
Amazon Linuxにて再度確認してみます。

**Comment by mikoto20000** [comment]
yamagonさん、その後進展はありますでしょうか？
問題ないようでしたら、Issueをクローズしたいと思います。

**Comment by yamagon** [comment]
$B$4O"MmCW$7$^$;$s$G?=$7Lu$4$6$$$^$;$s$G$7$?!#(B
$B860x$O!"BgJQ$_CQ$:$+$7$$FbMF$G(B
$BL5NA$N(BEC2$B$G$O!"%a%b%j!<$,ITB-$7$F(Bpassenger$B$,%3%s%Q%$%k%(%i!<$r5/$3$7$F$_$j$^$7$?!#(B
$B8f=u8@$G5$IU$-$^$7$?!#(B
$BM-$jFq$&$4$6$$$^$7$?!#(B
$B%/%m!<%:$r8f4j$$CW$7$^$9!#(B
2014/02/27 13:28 "mikoto20000" notifications@github.com:

**Comment by mikoto20000** [comment]
すいません、おそらくメールでお返事いただいたのだと思いますが、文字化けしているので、GitHubのWebサイトからコメントをお願いできますか？

よろしくお願いします。

**Comment by yamagon** [comment]
ご連絡致しませんで申し訳ございませんでした。
原因は、大変お恥ずかしい内容で
無料のEC2では、メモリーが不足してpassengerがコンパイルエラーを起こしておりました。
御助言で気付きました。
有り難うございました。
ubuntu,AWSLinuxとも動作致しました。
クローズを御願い致します。

**Comment by mikoto20000** [comment]
Ubuntuでも動いたのですね。ホットしました^^

原因がメモリ不足ですか、なるほど。
メモリが少ない場合は、エラーメッセージを出すようにした方がいいですね。
対応するまではオープンしたままにしておきます。

**Comment by esashi** [comment]
その変更だとAWS無料枠でインストールできなくなるような...

マイクロインスタンスではswpを設定すれば動作するので、もったいないと思います。

**Comment by mikoto20000** [comment]
esashiさん、コメントありがとうございます。上記修正でいかがでしょうか？
よろしくおねがいします。

**Comment by esashi** [comment]
これなら問題なさそうです。

変更頂きありがとうございました。

**Comment by mikoto20000** [comment]
では、クローズします。今後ともよろしくおねがいしますm(__)m
