### ISSUE TITLE
カスタムフィールド／ドロップダウンリストの項目数制限

### ISSUE THREAD

**Issue by yamagon** [alminium/alminium#123]
質問です。
ドロップダウンリストの項目数は１００個で制限が設けられているようですが
この個数を解除するには、設定変更で可能でしょうか。
それともコード変更が必要となるでしょうか。

初心者の質問で申し訳御座いませんが、教えて頂けないでしょうか。

**Comment by mikoto20000** [comment]
ALMiniumというより、Redmineの制限ですね。ソースコードを調べてみないと分からないですね、、、
時間が取れればみてみます。

**Comment by mikoto20000** [comment]
メニューの「管理」＞「設定」＞「全般」＞「ページ毎の表示件数」を変更
すると、変更できそうでしょうか。

よろしくお願いします。

**Comment by yamagon** [comment]
$B8f2sEzM-$jFq$&8f:B$$$^$9!#(B
Redmine$B$N5!G=$^$G<ALd$7$F$7$^$$?=$7Lu8f:B$$$^$;$s$G$7$?!#(B
$B@Z$jJ,$1$,IT==J,$G$7$?!#(B
$B$_<j?t$r$_3]$1CW$7$^$9$N$G!"EvJ}$G%3!<%I$rD4$Y$F$_$^$9!#(B

2014$BG/(B4$B7n(B3$BF|(B 9:42 mikoto20000 notifications@github.com:

**Comment by mikoto20000** [comment]
メールでお返事頂いたようですが、文字化けしているようです。
すいませんが、Webから入れなおして頂けますか？

**Comment by yamagon** [comment]
御回答有り難う御座います。
Redmineの機能まで質問してしまい申し訳御座いませんでした。
切り分けが不十分でした。
お手数をお掛け致しますので、当方でコードを調べてみます。
