### ISSUE TITLE
CentOS 6.3 + yum UpDate でrubyzipのエラー

### ISSUE THREAD

**Issue by raikou** [alminium/alminium#124]
いつも、とても便利に使わせていただいています。

今回、CentOSで以前簡単にインストールできたため、Jenkinsのテスト環境を作成しようと再度インストールを行ったところ以下のエラーが出ました。

＃環境は
CentOS 6.3 + yum UpDate + SSL + Jenkins + Gmail + VM
（VM利用ディスク：CentOS-6.3-x86_64-bin-DVD1.iso）
# sudo bash ./smelt

を行った際に起こります。
（キーボード設定を日本語に変更して、シャットダウンしています。）

「bundle update rubyzip」
を行った場合は、
「Could not locate Gemfile」
とのメッセージが出ます。

まだ、解決策など何も試行していない状態でチケットを上げさせていただいています。
本日（4/10 0：51）は時間がないため、日を追って解決策を模索したいと考えています。
もし、解決策などご存じでしたら教えていただきたい（対応していただきたい）と思い、投稿しています。

以上となります。

**\* ALMiniumのインストールコマンド ***
# cd /var/lib/
# yum　-y install git
# git clone https://github.com/alminium/alminium.git
# cd alminium
# git pull

**\* ALMiniumのインストールコマンドここまで　（2014/04/09の24時付近に施行）　***

**\* エラー内容　************************
You have requested:
  rubyzip = 1.0.0

The bundle currently has rubyzip locked at 1.1.3.
Try running `bundle update rubyzip`
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
Could not find gem 'zip-zip (= 0.2) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
cp: cannot create directory `public/plugin_assets/open_flash_chart': No such file or directory
/var/lib/alminium
**\* run initialize SQL ***
SELinuxが無効化されました
tcp 80番ポートのアクセスを許可しました
tcp 443番ポートのアクセスを許可しました
Stopping httpd:                                            [FAILED]

**_　エラー内容ここまで　**_

**Comment by FujiMountain** [comment]
こちらでも調査してみました。
プラグインインストールからBack logsを外すと
ALMiniumのインストールに成功します。
最近Back logsで何かを更新されたみたいですが、それが原因かも
しれません。

**Comment by raikou** [comment]
調査ありがとうございます。
とても助かります。

Back logsですか、調べてみます。
ありがとうございます。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

masterブランチで動作するように修正しました。修正に伴いRedmineを2.4.5にバージョンアップしています。時間があればお試しください。

**Comment by mikoto20000** [comment]
ごめんなさい。インストールは成功しますが、実行すると下記のエラーがでます。

```
Backlogs printable cards: problem loading labels: No such file or directory @ rb_sysopen - /opt/alminium/plugins/redmine_backlogs/lib/labels/labels.yaml
/usr/lib64/ruby/2.1.0/psych.rb:463:in `initialize'
/usr/lib64/ruby/2.1.0/psych.rb:463:in `open'
/usr/lib64/ruby/2.1.0/psych.rb:463:in `load_file'
/opt/alminium/plugins/redmine_backlogs/lib/backlogs_printable_cards.rb:225:in `<class:CardPageLayout>'
/opt/alminium/plugins/redmine_backlogs/lib/backlogs_printable_cards.rb:57:in `<module:BacklogsPrintableCards>'
/opt/alminium/plugins/redmine_backlogs/lib/backlogs_printable_cards.rb:56:in `<top (required)>'
/opt/alminium/vendor/bundler/ruby/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
/opt/alminium/vendor/bundler/ruby/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
/opt/alminium/vendor/bundler/ruby/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
/opt/alminium/vendor/bundler/ruby/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
```

いましばらくおまちください、、、

**Comment by raikou** [comment]
お忙しいところ、修正ありがとうございます。

時間が無く、情報を提供できず申し訳ありません。

**Comment by mikoto20000** [comment]
修正を確認したのでクローズします。もし時間があれば最新版でお試し頂ければと思います。

よろしくお願いいたします。
