### ISSUE TITLE
IPAより 報告された脆弱性について

### ISSUE THREAD

**Issue by yamagon** [alminium/alminium#125]
Redmineにて脆弱性が報告されているようですが
alminiumでは、問題が発生しないでしょうか。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。具体的にどの報告でしょうか？下記のサイトを見ても
Redmineに関する報告は発見できませんでした。

http://www.ipa.go.jp/security/announce/alert.html

よろしくおねがいいたします。

**Comment by akiko-pusu** [comment]
こちらのことですよね。（JPCERTからも出ています）
http://jvndb.jvn.jp/ja/contents/2014/JVNDB-2014-000041.html

Masterで2.4.4に戻していますが、2.4.5か2.5.1にしたほうが良いかと思います。
BackLog側もまもなく修正が入るのではないかと思いますが、よければまた検証お手伝いします。

**Comment by mikoto20000** [comment]
akikoさん、ありがとうございます。あまり検証は進んでいませんが、redmine-2.5.xブランチにて、Redmine2.5.1が動作する状況にはなっています。

問題はなさそうですが、念のためご確認頂けるとありがたいです。よろしくお願いします。

**Comment by akiko-pusu** [comment]
わかりました。Vagrantで試すだけですが、レポートします。

**Comment by yamagon** [comment]
この修正で良いのではと。。。
 該当ソース：app/controllers/application_controller.rb 
 該当コード： 
 begin 
     uri = URI.parse(back_url) 
     # do not redirect user to another host or to the login or register page 

 誤  if (uri.relative? || (uri.host == request.host)) && !uri.path.match(%r{/(login|account/register)}) 
 正  if ((uri.relative? && back_url.match(%r{\A/\w})) || (uri.host == request.host)) && !uri.path.match(%r{/(login|account/register)}) 

```
     redirect_to(back_url) 
     return 
 end 
```

御確認をお願い致します。

**Comment by mikoto20000** [comment]
yamagonさん、コメントありがとうございます。

ALMiniumは、インストーラとして動作しているので、対応としてはRedmineのバージョンを上げる方が簡単なのです。この問題とは別にRedmineのバージョンアップ自身が課題だったので、これを機に最新版で動作するように修正しました。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
修正版の動作確認に手間取ってしまいましたが、修正したバージョンをmasterにマージしたのでクローズします。
対応がおくれてすみません。ご報告ありがとうございました。
