### ISSUE TITLE
80番ポート以外でのredmineの起動について

### ISSUE THREAD

**Issue by durswd** [alminium/alminium#127]
使わさせていただいております。
現在、Apacheの設定とbin/alm-sync-scmを書き換えlocalhostにポートを追加することで、
redmineを80番ポート以外で起動しているのですが、
そもそも公式では、80番ポート以外での起動はサポートしていないのでしょうか？

もしないのならば、機能追加を検討してくれるとありがたいです。
以上、お手数ですがよろしくお願いします。

**Comment by mikoto20000** [comment]
特にサポートしていないという訳ではありませんが、ご認識の通り設定ファイルとスクリプトの書き換えは必要ですね。もし、具体的なやり方の文書を頂ければ、FAQに追加したいと思います。

よろしくおねがいします。

**Comment by durswd** [comment]
返答ありがとうございます。

*80番ポート以外でalminiumを起動する方法
xxxxxのポート番号で起動する場合、

・alm-sync-scm
http://localhost/sys/を、http://localhost:xxxxxx/sys/　と変更

・/etc/apache2/sites-available/default
80をxxxxxに変更

・/etc/apache2/sites-available/redmine
80をxxxxxに変更

に変更し、apacheを再起動することによりポートを変更できます。
