### ISSUE TITLE
Redmineプラグインのバージョン指定方針

### ISSUE THREAD

**Issue by speg03** [alminium/alminium#130]
[Redmineのプラグインリスト](https://github.com/alminium/alminium/blob/dev/config/redmine-plugins.lst)でタグやコミットではなくブランチが指定されているのは、何か方針など決められているのでしょうか。

redmine_xls_exportプラグインのfeaturesブランチ指定などです。
#129 が発生した原因でもあるのですが、指定のブランチが更新されたときにインストールが失敗する可能性があるのはちょっと辛いなと思っています。

**Comment by mikoto20000** [comment]
基本的には、
1. タグで提供されているものはタグで
2. タグの最新版で動かないものはブランチの先頭で動作すればブランチを

指定しています。あとは、ブランチの先頭で動作しなかった場合は、過去のコミットで動作するものを探したり、alminiumプロジェクトでフォークして手直ししたりという感じです。

ご迷惑をお掛けして申し訳ありませんが、できるだけ固定するようにしたいと思います。

**Comment by speg03** [comment]
了解です。
2. の場合はブランチ指定ではなく、そのブランチの先頭コミットを指定すると良いと思います。
