### ISSUE TITLE
インストール失敗：Caused by: hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/

### ISSUE THREAD

**Issue by HitoshiUezu** [alminium/alminium#134]
アップデートセンタから reverse-proxy-auth-plugin をインストールします。
Caused by: hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/plugins/reverse-proxy-auth-plugin/1.4.0/reverse-proxy-auth-plugin.hpi
を繰り返します。

環境は、http://localhost:8080/jenkins/jnlpJars/jenkins-cli.jarの無限ループに苦しんだのでCentOS6.5をクリーンインストール、
yum -y update
yum -y git
ruby/gems/bundleなどは何も入れず。
git clone https://github.com/alminium/alminium.git
cd alminium
./smelt
を実施。

インストール中のログで
gem: コマンドが見つかりません
bundle: コマンドが見つかりません
は出たものの、/jenkins-cli.jarの無限ループは脱した様に見受けられます。
次回クリーンインストールの時は、gem/bundleをインストールしようと思いますが
Caused by: hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/はそれで解消されるものでしょうか？

**Comment by HitoshiUezu** [comment]
すみません、解決しました。
alminiumフォルダを削除して、以下一連の作業を行い、無事インストールできました。
OSのクリーンインストール前は以下をやると/jenkins-cli.jarの無限ループで苦しんだのですが
理由不明ですが複合要素でできなかったみたいです。
OSクリーンインストール、gitと以下を足せば、OKですね。
tar zxvf ruby-2.1.2.tar.gz
cd ruby-2.1.2
./configure
make
make install

tar xzf rubygems-1.8.25.tgz 
cd rubygems-1.8.25 
ruby ./setup.rb

bundlerのインストール
gem install bundler --no-rdoc --no-ri

Passengerのインストール

# gem install passenger --no-rdoc --no-ri

# passenger-install-apache2-module

http://little-braver.com/346/を参考にしました。

**Comment by mikoto20000** [comment]
お返事が遅くなりすみません。プロキシを利用した場合で、プロキシに認証が不要な場合、正しく動作しない不具合がありました。

修正しましたので、最新版では問題なくインストールできると思います。お手数お掛けしました。
