### ISSUE TITLE
インストール失敗: undefined method `height=' for class `Spreadsheet::Row'

### ISSUE THREAD

**Issue by tukiyo** [alminium/alminium#136]
docker上のCentOS6.5でセットアップを行ったところ以下エラーで完了しません。

もしdockerをお使いでしたら以下コマンドで再現できます。

```
docker run -it tukiyo3/centos6-ja-alminium /bin/bash
cd /opt/alminium/
USER=root bash ./smelt
```

[ログファイル](https://github.com/tukiyo/sample/blob/master/tmp/alminium_errorlog.txt)

```
rake aborted!
undefined method `height=' for class `Spreadsheet::Row'
/opt/alminium/vendor/bundler/ruby/2.2.0/gems/spreadsheet-0.9.7/lib/spreadsheet/row.rb:25:in `alias_method'
```

お手数ですがご確認お願いします。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

> /opt/alminium/vendor/bundler/ruby/2.2.0

このログから、Ruby2.2.0を利用しているように見えます。DocketのCentOSはRuby2.2が最初から入っているのでしょうか？

ALMiniumはRubyが入っていなければインストーラがRuby2.1をインストールするようになっており、
また、Ruby2.1でしか動作確認をしておりません。

まずは、下記のコマンドでお使いのRubyのバージョンをご確認ください。

 # ruby --version

**Comment by tukiyo** [comment]
DocketのCentOSはRuby2.2を入れていました。
Ruby2.1にして再度確認してみます。

**Comment by tukiyo** [comment]
CentOS6.5、Ruby2.1.2にして再度挑戦しました。
先に進みましたが、今度はmod_passenger.soがビルドされていないのか見つかりません。
[ログファイル](https://github.com/tukiyo/sample/blob/master/tmp/alminium_errorlog2.1.txt)

(現在の様子を tukiyo3/centos6-ja-alminium にpushしました。前回と同様の方法で確認ができます。)

お手数ですがよろしくお願いします。

**Comment by akiko-pusu** [comment]
passengerはメモリが少ないとうまくビルドできないケースがあるのですが、dockerの環境があるので試させていただきますね。

**Comment by tukiyo** [comment]
Ruby2.1.2で作業 (docker run -it tukiyo3/centos6-ja-alminium /bin/bash)
- [passenger-install-apache2-module](https://github.com/tukiyo/sample/blob/master/tmp/alminium_errorlog2.2.txt)のログ
- [strace passenger-install-apache2-module](https://github.com/tukiyo/sample/blob/master/tmp/alminium_errorlog2.3.txt)のログ

Ruby2.1.0で作業 (docker run -it tukiyo3/centos6-ja-alminium-test2 /bin/bash)
- [bash smeltの初回実行ログ](https://github.com/tukiyo/sample/blob/master/tmp/alminium_errorlog2.4.txt)

**Comment by mikoto20000** [comment]
追加情報ありがとうございます。

ALMiniumのインストーラはスクリプト実行時にどのステップまで進んだか、*.installedファイルを作って管理しています。最初のインストールで失敗したときに、gemのインストールが完了したことを示すgem.installedファイルが残っているため、gemのインストールがスキップされ、gemインストールでインストールされるはずのpassengerもインストールされてなかったと思われます。

\ # sh uninstall

を実行して、すべてyを入力すると、お使いのOSをクリーンな状況に戻してくれます。きれいな状態にしてからもう一度お試しください。

**Comment by tukiyo** [comment]
`sh uninstall`を試してから再度`smelt`を実行しましたが、
`passenger-install-apache2-module`が先ほどと同じく成功しませんでした。

passengerのgemは入っているようです。

```
# gem list | grep passenger
passenger (4.0.45)
```

**Comment by akiko-pusu** [comment]
index.docker.ioの公式centosイメージを使ってセットアップしてみます。
よければ、追加モジュールとかyumの確認をして、Jenkinsなし、Firewallなし、httpsなしの構成で上がるかどうかご報告しますね。
 わたしがよく失敗したパターンは、Apacheへのpassengerの組み込みの失敗（メモリ不足とか）、プラグインのリポジトリとRedmineのGemのバージョンが合わなくなった、sudoのPATHの設定がダメだったとか、です。

**Comment by tukiyo** [comment]
dockerを使わずVirtualBoxでCentOS6.5 x86_64 + ruby2.1.0で試してみましたが、同じエラーが出ました。

```
Location of apxs2: /usr/sbin/apxs
Unable to autodetect the currently active RVM gem set name. This could happen if you ran this program using 'sudo' instead of 'rvmsudo'. When using RVM, you're always supposed to use 'rvmsudo' instead of 'sudo!'.

Please try rerunning this program using 'rvmsudo'. If that doesn't help, please contact this program's author for support.
which: no rake2.0 in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/rvm/bin/:/usr/local/rvm/rubies/ruby-2.1.0/bin/)
```

**Comment by tukiyo** [comment]
rvmで事前にrubyをビルドしてからsmeltを実行していたのが原因でした。
以下手順で無事入りました。

```
docker run -it tukiyo3/centos6-ja /bin/bash

yum install --enablerepo=centosplus -y openssl-devel
yum install -y git which tar libyaml

cd /opt
git clone https://github.com/alminium/alminium.git
cd alminium
USER=root bash ./smelt

yum clean all
```

**Comment by tukiyo** [comment]
```
mkdir -p $HOME/alminium/files/
mkdir -p $HOME/alminium/mysql/

docker run \
 -i \
 -p 80:80 \
 -v $HOME/alminium/files/:/opt/alminium/files/ \
 -v $HOME/alminium/mysql/:/var/lib/mysql/ \
 -t tukiyo3/centos6-ja-alminium /bin/bash
```

でalminiumが動作するイメージをpushしました。昨日UPしたデバッグ用イメージは削除しました。

**Comment by mikoto20000** [comment]
無事動いてよかったです。

なるほど、事前にrvmでrubyをインストールしていたのですね。
ALMiniumは初心者向けにCentOSを入れた素の状態からインストーラを叩けば
Ruby環境含め全てセットアップしてくれるようになっています。

Dockerはまだ使ったことありませんが、このイメージをインストールすれば直ぐに
ALMiniumが起動する感じでしょうか？
時間があるときに、試してみたいと思います。

**Comment by tukiyo** [comment]
はい、ALMiniumが起動します。[こちらも参考](http://qiita.com/tukiyo3/items/f07df454c85e4e8a0ef3)

**Comment by akiko-pusu** [comment]
確認のご報告くらいしかできませんが動きました！とても便利なので大変嬉しいです。
