### ISSUE TITLE
英語化

### ISSUE THREAD

**Issue by yousukeitoh** [alminium/alminium#139]
利用させていただいております。
最近非日本語圏のメンバーが加入したため、ALMiniumのページ中の表記を英語にしたいのですが、"Administration"の"Default Language" を "English"、"My Account"の "Language"を "English"としても一部に日本語が残ります。（たとえば、"Project"の"Overview"のページを見ると、「バグ」、「開発者」、「タスク」など）。細かいことで恐縮ですが、これらはどのようにすれば英語に変更できますでしょうか？

**Comment by mikoto20000** [comment]
バグ、タスクなどは、トラッカーの分類ですが、トラッカーの名前は言語設定では変更することはできません。

Administration>Trackerからトラッカーの名前を変更してください。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
開発者、管理者などの名前は、

Administration > Roles and permissions

から変更することができます。

**Comment by yousukeitoh** [comment]
ご回答ありがとうございます。大変助かりました。
どこかソースに書いてあるものかと思って、そちらばかりを探しておりました。
