### ISSUE TITLE
ファイルとディレクトリ構成を整理しましょう

### ISSUE THREAD

**Issue by tkmtmkt** [alminium/alminium#151]
インストール処理を以下のようにする方向でファイルとディレクトリ構成を整理してはどうでしょう。
- OS判定を `/etc/os-release` で判定するようにする（Linuxの場合のみ）  
  ⇒ファイルがあればLinux、なければ個別の判定を追加といった感じで
- パッケージインストール用スクリプトは `ID_LIKE (rhel、debian)` 毎に用意する
- パッケージリストは `ID + VERSION_ID` 毎に用意する  
  ⇒使いたい人が随時追加できるようにディレクトリを分けておく
- apache設定ファイルは2.2系と2.4系の両方に対応できるようにする  
  ⇒passengerの設定はredmine.confから分離して自動生成すればよい
- redmine、jenkinsの設定は全プラットフォーム共通

**Comment by mikoto20000** [comment]
プルリクエスト#156によりクローズします。
