### ISSUE TITLE
importer

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#16]
1.4.xで動作するか確認

**Comment by drakontia** [comment]
fastercsvを使用しているが、Ruby 1.9.2からは標準ライブラリに　csv parserがあるらしく、そちらを使うのを推奨された。

**Comment by drakontia** [comment]
Upstreamで修正したものがマージされました。
問題なく動くはずです。下位互換性は考慮していないですが。

**Comment by mikoto20000** [comment]
プラグインを有効化しました。クローズします。
