### ISSUE TITLE
alminiumインストール passenger5.0.4でのapache起動失敗

### ISSUE THREAD

**Issue by cyberblack28** [alminium/alminium#169]
alminiumインストール最後のhttpdの再起動で以下のエラーで失敗します。

Syntax error on line 5 of /etc/httpd/conf.d/maven.conf:
Invalid command 'PassengerEnabled', perhaps misspelled or defined by a module not included in the server configuration

/etc/httpd/conf.d/maven.confの以下の箇所をコメントアウトするとhttpd自体は起動できますが、
ブラウザでアクセスするとapacheの初期インストール時の画面が表示されるだけで、alminiumのログイン画面が表示されません。

Alias /maven /var/opt/alminium/maven
<Directory /var/opt/alminium/maven>
  Allow from all
  Options +Indexes
  #PassengerEnabled off
</Directory>

/etc/httpd/conf.d/redmine.confを開いてみると空ファイルとなっています。

昨晩は問題なくインストールできて利用できました。
本日再インストールを実施したら上記の状況です。

おそらく、passengerのバージョンが5.0.2から5.0.4に上がったことが原因のように思えます。

今のところ解決策が見えない状況でございます。

jenkinsは問題ありません。

環境
centos6.6
httpd:httpd-2.2.15-39.el6.centos.x86_64
ruby:ruby-2.1.2-2.el6.x86_64
rubygems:2.2.2
mysql-server:mysql-server-5.1.73-3.el6_5.x86_64

**Comment by tkmtmkt** [comment]
redmine.conf の先頭でpassengerモジュールをロードしているため、redmine.conf が空ファイルになっていると、PassengerEnabledがエラーになります。

redmine.confが存在することから、inst-script/rhel6/post-installまでは実行されていて、空ファイルであることからsedの処理で失敗しているものと推測されます。

手作業での修正は以下の通り。
1. `inst-script/rhel6/httpd-redmine.conf` を `/etc/httpd/conf.d/redmine.conf` にコピーする。
2. `/etc/httpd/conf.d/redmine.conf` を開いて `%PASSENGER_VERSION%` と `%HOSTNAME%` を修正する。

**Comment by cyberblack28** [comment]
ありがとうございます。
解決いたしました。
