### ISSUE TITLE
hudson

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#17]
1.4.xで動作するか確認

**Comment by drakontia** [comment]
https://bitbucket.org/nobiinu_and/redmine_hudson

入れてみたのですが、動いているようです。
Jenkinsへのリンクと、Redmine側からジョブ実行できればOKですか？

**Comment by mikoto20000** [comment]
はい。それで十分だと思います。よろしくお願いします。

**Comment by mikoto20000** [comment]
Redmine2.2に対応してもらいました。
