### ISSUE TITLE
backlogs

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#19]
1.4.xで動作するか確認。

**Comment by mikoto20000** [comment]
v0.9.1ではマスターバックログのJavaScriptが同和しないようです。

**Comment by drakontia** [comment]
JavaScriptの部分ってのは、プルダウンメニューですか？
それだと、自分のコミットが受け入れられれば、動きます。

**Comment by mikoto20000** [comment]
既に取り込まれてv0.9.2が出ていますね。

最新版で動作することを確認しましたのでクローズします。

**Comment by drakontia** [comment]
最近の本家の動きが早くて、驚いています（笑
ただ、リリースのところがまだ新規作成と編集ができないので、
なんとか直したいところです。

**Comment by mikoto20000** [comment]
インストール時に下記のメッセージとともにbacklogsの初期化に失敗しているようです。

```
rake aborted!
(/opt/alminium/vendor/plugins/redmine_backlogs/config/locales/ja.yml): found character that
cannot start any token while scanning for the next token at line 27　column 32
```

**Comment by mikoto20000** [comment]
修正のプルリクエストをアップストリームへ送信しました。

**Comment by drakontia** [comment]
リリースのところ直したので、プルリクエスト送っときました。

**Comment by mikoto20000** [comment]
ありがとうございます。

backlogsはまだ何か出てきそうなので、もう少しオープンにしておきます。

**Comment by mikoto20000** [comment]
最新のmasterでは、初期インストールの状態で、設定エラーのメッセージが表示されるようになっています。

また、ストーリーとタスクのトラッカーも設定されなくなっています。

ストーリーとタスクを設定しても設定エラーのメッセージが消えず、バックログが使えません。

**Comment by mikoto20000** [comment]
インストール時に下記のメッセージとともにbacklogsのインストールに失敗していることが判明しました。

```
Migrating redmine_spent_time_column...
Migrating rfpdf...
Cannot find old migration table - assuming nothing needs to be done
rake aborted!
1.4.1.stable (UNSUPPORTED ruby version 1.9.3)

Tasks: TOP => redmine:backlogs:install

(See full trace by running task with --trace)
rake aborted!
undefined method `generate_burndown' for #<Class:0x00000005cf8578>

Tasks: TOP => redmine:backlogs:generate_chart_data
(See full trace by running task with --trace)
```

**Comment by mikoto20000** [comment]
generate_chart_dataでエラーになっていたので、外しました。最近のBacklogsでは不要のようです。
また、タスクとストーリーの設定でエラーになっていたので、これらの設定も外しました。

```
-rake redmine:backlogs:install task_tracker=サポート story_trackers=機能 labels=false
-rake redmine:backlogs:generate_chart_data
+#rake redmine:backlogs:install task_tracker=サポート story_trackers=機能 labels=false
```

backlogsの設定のSQLが正しく動作しなくなっていたので、修正しました。

```
+#UPDATE settings SET name='plugin_redmine_backlogs', value=' --- \n:points_burn_direction: down\n:taskboard_card_order: story_follows_tasks\n:ca
+REPLACE INTO settings(name,value,updated_on) VALUES ('plugin_redmine_backlogs',' --- \n:points_burn_direction: down\n:taskboard_card_order: stor
```

ただし、これらの修正をしても、常時画面上にBacklogsの設定エラーが表示されます。v0.9.4ではエラーが発生せずに、v0.9.5以降でエラーが発生していることから、この間の変更がなんらかの影響を与えていると思います。

引き続き原因を調べます。

**Comment by komarisu** [comment]
backlogsのセットアップの手間が省けそうだと思いalminiumをインストールしたgithub初心者です。
トップページの手順に従って、AWSのクリーンなCentOS6.2にセットアップしたのですが、backlogsがうまく動作していないようです。
バージョンを見るとv0.9.15となっており、上記の議論のバージョンよりも古いようです。
デフォルトでセットアップした後、どのような作業を行えばみなさんのようにbacklogsを動かせるようになるでしょうか？
お手数をおかけしますが、ご教示ください。

また、紹介ページに次の情報を書いた方が良いかもと思いました。
・CentOS6.2(ただし64bit版のみ)：最初32bit版にセットアップして見事に失敗しました。
・64bit版に入れても、起動させるとapacheのログにmod_wsgiのPythonのバージョンが違うとのエラー。これは自分でmod_wsgiをmakeして入れ替えれば解決できるのですが、初心者向けに別途makeしなくても済むようになっていると有難いかと思いました。

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。

どのブランチでお試しでしょうか?時間があればdevブランチで試してみていただけますか?
また、次回からドキュメントやmod_wsgiなどこのIssueに関係ないものは新たにIssueを作成していただけると管理上楽にになってありがたいです。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
すいません、追加で1点

> また、紹介ページに次の情報を書いた方が良いかもと思いました。
> ・CentOS6.2(ただし64bit版のみ)：最初32bit版にセットアップして見事に失敗しました。

README.mdには64ビット版を使うように書いていますが、紹介ページとはどこのことを指していますか?

よろしくお願いします。

**Comment by komarisu** [comment]
早速返信いただきありがとうございます。Issueを分ける件申し訳ありません。
git自体使い慣れていないので、branchの確認方法も怪しいのですが、次のコマンドの結果を以下に。
git branch
master
でした。devブランチというのはgit branch -aで見える
remotes/origin/dev
のことでしょうか？

また、追記コメントの紹介ページですが、公式の
https://github.com/alminium/alminium
にはしっかり記述されていたので、これは私が外部の紹介ブログや記事などを
起点にして公式ページの内容をちゃんと読まなかったせいで勘違いしたと判明です。
すいません。

**Comment by mikoto20000** [comment]
> でした。devブランチというのはgit branch -aで見える
> remotes/origin/dev
> のことでしょうか？

そうです。

```
$ git checkout dev
```

でbranchを切り替えることができます。

64ビットの記述の件も了解しました。よろしくお願いします。

**Comment by komarisu** [comment]
dev版を試してみました。
master版と異なり、リリース計画のページが見えるようになったので、backlogsも動くかと期待したのですが、まだうまく動いていない？感じです。（バックログの使い方を間違っているのかもしれませんが。もしもバックログのチュートリアル的なサイトをご存知でしたらご教示ください）
具体的には、プロダクトバックログの左端のドロップダウンメニューから新しいストーリーやスプリントを追加しても、その場でアイテムは表示されますが、状態が保存されていないので、プロジェクトのページへ戻って再度バックログのページへ行くと真っ白に戻る状態です。
プロジェクトの設定のバージョンに値を入れるとスプリントが表示されることもわかりましたが、ここで登録した物しかバックログで使えないという仕様ではないと思いますし・・・。
もしも解決の方法をご存知でしたらご教示ください。

**Comment by mikoto20000** [comment]
> 具体的には、プロダクトバックログの左端のドロップダウンメニューから新しいストーリーやスプリントを追加しても、
> その場でアイテムは表示されますが、状態が保存されていないので、プロジェクトのページへ戻って再度バックログ
> のページへ行くと真っ白に戻る状態です。

私の環境では、正しく登録できています。ALMiniumをクローンしたディレクトリで、

```
# sh uninstall
```

として、全てにYと答え、一度ALMiniumの環境をクリーンにして上で、もう一度インストールしなおしてみても同じ状況になるでしょうか?

よろしくお願いします。

**Comment by mikoto20000** [comment]
最近のバージョンはbacklogsはそれなりに安定して動作するのでクローズします。
