### ISSUE TITLE
drafts

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#24]
1.4.xの動作確認

https://github.com/jbbarth/redmine_drafts.git

**Comment by drakontia** [comment]
ドラフトを保存しましたという文言は出るが、どうやって保存先を確認するか考え中。

**Comment by mikoto20000** [comment]
jbbarthブランチで2.0.x対応をしている?

**Comment by mikoto20000** [comment]
jbbarthさんのブランチが動作したのでそれを採用します。
