### ISSUE TITLE
attach_screenshot

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#25]
1.4.xで動作確認

master,https://github.com/alminium/redmine_attach_screenshot.git

**Comment by drakontia** [comment]
ftoolsメソッドが廃止されたので、fileutilsに変更する必要があります。

**Comment by drakontia** [comment]
fileutilsに変更してもrake db:migrateでabortedされる。
config/routes.rbがないせいだと思われる。

**Comment by mikoto20000** [comment]
haru_iidaさんにより修正されたのでクローズします。
