### ISSUE TITLE
charts

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#29]
1.4.xで動作確認

https://github.com/cforce/redmine_charts.git

**Comment by drakontia** [comment]
Ruby 1.9.3では、Stringのsplitメソッドが廃止されたため、動作しません。

**Comment by drakontia** [comment]
すいません。splitメソッドはあるようです。

```
NoMethodError (undefined method `split' for #<Project:0x00000004b56338>):
```

@Projectの変数から返ってくる値がRedmine1.4になって変わったせいで上手く処理できていないみたいです。

**Comment by drakontia** [comment]
パッチ当てている人がいました。
https://github.com/kanterov/redmine_charts

日本語ファイルの修正も必要だったので、修正しています。
https://github.com/drakontia/redmine_charts/tree/RM1.4.x

記録時間分布のところはまだエラーが出ています。

**Comment by mikoto20000** [comment]
マイルストーンをredmine 2.0.xに変更。drakontiaさんのブランチで開発中?

**Comment by drakontia** [comment]
遅くなりましたが、developブランチのがredmine 2.0.xで動くようになりました。prototype.jsからjQueryになったことによる微細な問題を除けば、Redmine 2.1.xでも動作しています。個人的にはテストの部分も現状に合わせられるようにしたいなと思っていて、それがmasterブランチへマージしていない理由です。

**Comment by mikoto20000** [comment]
Redmine 2.1.xで動かすと結構エラー吐いてますね。prototype.jsのコードをjQueryへポーティングする必要がありそうです。

**Comment by drakontia** [comment]
本当ですか！？フィルターが隠れていないところしかエラー吐いてないと思ってました。もっとよく探してみます。しかし、RubyだけでなくjQueryもか。ぐもも。。。

**Comment by mikoto20000** [comment]
まだバグがあるかもしれませんがフィルタ回りを中心にちょっと直してみました。下記のhackブランチにコミットしています。

https://github.com/alminium/redmine_charts

よかったら、これをベースに2.1.x対応を進めて頂けるとありがたいです。

**Comment by drakontia** [comment]
バージョンだけ変えさせて頂きましたが、2.1ブランチ取り込みました。あとはbacklogsとgemがかぶるのを回避するうまい方法があればといったところです。

**Comment by mikoto20000** [comment]
修正ずみです。
