### ISSUE TITLE
複数ファイルの添付ができない(redmine_attach_screenshot 利用時)

### ISSUE THREAD

**Issue by akiko-pusu** [alminium/alminium#3]
こちらのリポジトリから、単体でredmine_attach_screenshot をダウンロードして導入してみました。

この場合、通常の添付ファイルの機能のうち、「別のファイルを追加する」ことができなくなっています。
（リンクをクリックしても、追加のファイルアップロードフォームが表示されない）

Redmineのバージョンアップにともなって、ファイルアップロードのフォームに、HTMLの要素が追加されたようです。

<span id="attachment_description_label_content"><%= l(:label_optional_description) %></span>を追加すると、ファイルの複数添付がOKになっています。

**Comment by mikoto20000** [comment]
akiko-pusuさん

ご報告ありがとうございます。上記の変更、下記のリポジトリへのプルリクエストで頂ければ修正いたします。

https://github.com/alminium/redmine_attach_screenshot

twitterで頂いているscreenshot.pngというファイル名が重複する件ですが、ざっと調査した限りJavaAppletの中と、プラグイン用のコードを幾つか修正する必要があるようです。あと、Appletのソースコードは見当たらないで、逆コンパイルして書き直す必要がありそうです。

Javaの開発環境が手持ちでないので、対応はちょっと時間が掛かると思います。

よろしくお願いいたします。

**Comment by akiko-pusu** [comment]
mikoto20000さん、ありがとうございます。

＞screenshot.pngというファイル名が重複する件

なのですが、大きな問題でないのであれば、そのままでも良いのかもしれません。
（Wikiにまで貼りつけるケースが少ないのであれば）

私の環境では、ひとまず下記のようにして修正しています。

ファイル：

## redmine_attach_screenshot/lib/attachment_hook.rb

```
  def file.original_filename
    "screenshot.png"
  end
```

---

## を、

```
  def file.original_filename
    File.basename(path())
  end
```

---

に変更。

これでひとまず、userid_HHMMSS_screenshot.png という１チケットに対しユニークな名前でアップできるようになっています。
あまり綺麗ではないのですが...。
また、コメント入力欄のそばにある、雷マーク（？）をクリックすると、Wikiのフォームには上記のとおり、!userid_HHMMSS_screenshot.png! とペーストされます。
ひとまずそのままでチケット作成／更新して、添付ファイルの画像も表示されるようになっています。

**Comment by mikoto20000** [comment]
なるほど。もっと面倒かと思っていたのですが、それだけで治るんですね。ありがとうございます！！

あと、

```
<%= l(:label_optional_description) %>を追加すると、
```

は、何処に追加すればいいか教えてもらえますか?

よろしくお願いします。

**Comment by mikoto20000** [comment]
> あと、
> <%= l(:label_optional_description) %>を追加すると、
> は、何処に追加すればいいか教えてもらえますか?

教えて頂いた方法とは異なるのですが、下記のspan id="attachment_description_label_contentを追加することにより解決できることが確認できました。

```
<span id="attachment_description_label_content"><%= l(:label_optional_description) %></span>
```

ご連絡ありがとうございました。

**Comment by akiko-pusu** [comment]
確認しました、リポジトリも調整して下さって、ありがとうございます。
（差分をお送りすればよかったのですが、すみません！）

こちらのユーザの要望で、スクリーンショットの画面をポップアップさせるボタンを、画像（アイコン）に変えています。
自分でつくったアイコンなので、もしよかったら別途Pull Requestさせていただくかもしれません。

それでは！

2011年11月19日6:46 mikoto20000
reply@reply.github.com:

**Comment by mikoto20000** [comment]
了解しました。お待ちしています！！
