### ISSUE TITLE
Redmine.pm+git-http-backendの動作確認

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#35]
ALMiniumのRedmine.pmは、git-http-backend対応パッチを当てたものを利用しています。

Redmine1.4.xから1プロジェクトマルチリポジトリに対応しているので、次のどちらかの対処を行わないと正しく認証が動作しません。
1. Redmine1.4.xのRedmine.pmをgit-http-backend対応にする
2. ALMiniumのRedmine.pmをマルチリポジトリ対応にする

多分、1の方式がいいと思いますが、検討・実装・動作確認が必要です。

**Comment by drakontia** [comment]
すでにパッチがでていて、動作も確認されているようです。
http://www.redmine.org/issues/4905

Ruby 1.9.xかどうかは記載ないので、ALMiniumでの動作確認は必要です。

**Comment by mikoto20000** [comment]
ありがとうございます。取り敢えず入れ換えてみました。
(検証はまだです)

**Comment by mikoto20000** [comment]
メインリポジトリは認証が正しく効くようですが、それ以外のリポジトリの認証がうまく通って無い感じがします。

**Comment by drakontia** [comment]
confファイルを参照先のと入れ替えてみるか、
プロジェクトの「設定」→「リポジトリ」でサブリポジトリでのユーザの関連付けができているか、（ユーザ名とメールアドレスが一致すれば自動的になるようですが）
あたりはいかがでしょうか。
今、メイン環境がNginxになっていて検証手伝えなくてすいません。
