### ISSUE TITLE
インストール時エラー

### ISSUE THREAD

**Issue by drakontia** [alminium/alminium#4]
こんにちわ。
Redmineを最近使い始めて今までは直接導入してましたが、
オールインワンのがあると知りまして使わせて頂きました。

VMware上のCent OS 6.2にてbash ./smeltを実行したところ
インストール途中にてi18nがないというメッセージが出てきました。
インストール自体は終了しましたが、サイトに接続してもエラーが返ってきました。
# rake generate_session_store
# rake db:migrate RAILS_ENV=production

上記のコマンドを実行したところ、正常にサイトにログイン出来る様になりました。

致命的ではありませんが、とりあえずご報告までに。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。ちなみに、masterブランチでお試しでしょうか。

i18nのgemがないというエラーと上記のコマンドは必ずしも関連性はないように思いますね。
(上記のコマンドでi18nのgemが入る訳ではないので)

ちょっと頂いた情報からだけでは、原因が分かりません。サイトに接続したときに出たエラーがあれば頂けるとありがたいです。

ちなみに、devブランチではRedmine1.3.1対応のものがリリース直前の状態なので、よろしければこちらも使ってみてください。

**Comment by drakontia** [comment]
お返事ありがとうございます。

masterブランチで試してみました。
エラーは保存して無くてですね…

別にサーバを作成し、改めてインストールしてみました。
前回と同じようにmasterと、dev。ついでにRedmineのインストールをzipダウンロードではなく
Subversionから変更したものでやってみました。
ログはこちらです。http://db.tt/AzxpOerP

再現するのかとおもいきや、どれも同じようにmysql.rbがないとなってしまい、
最後のhttpd restartも失敗してしまいました。
途中のmysqlのCREATE USERで失敗しているのか。
（ERROR 1396 (HY000) at line 2: Operation CREATE USER failed for 'alminium'@'%'）

迷わせてしまってすいません。
