### ISSUE TITLE
AmazonAMI 32bit/64bit でインストール後にトップ画面でエラー表示する。

### ISSUE THREAD

**Issue by bomber555** [alminium/alminium#48]
お世話になります。

早速インストールしようと思いましたが、半日悩んで挫折しました。

●使用OS
AmazonAMI 2011.09 32bit
AmazonAMI 2012.03 32bit
AmazonAMI 2011.09 64bit
AmazonAMI 2012.03 64bit
CentOS Linux release 6.0 (Final) 32bit

●インストール手順
 # yum install git 
 # git clone https://github.com/alminium/alminium.git
 # cd alminium
 # bash ./smelt
SSL: y
Secutiry: y

この後、ウェブアクセスすると下記エラー発生。

●エラー内容
ウェブページに表示された内容です。

Ruby on Rails application could not be started

These are the possible causes:
There may be a syntax error in the application's code. Please check for such errors and fix them.
A required library may not installed. Please install all libraries that this application requires.
The application may not be properly configured. Please check whether all configuration files are written correctly, fix any incorrect configurations, and restart this application.
A service that the application relies on (such as the database server or the Ferret search engine server) may not have been started. Please start that service.
Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.
Error message:
uninitialized constant RedmineApp
Exception class:
NameError
Application root:
/opt/alminium
Backtrace:
# File    Line    Location

0   /opt/alminium/vendor/rails/activesupport/lib/active_support/dependencies.rb 469 in `load_missing_constant'
1   /opt/alminium/vendor/rails/activesupport/lib/active_support/dependencies.rb 106 in`const_missing'
2   /opt/alminium/vendor/rails/activesupport/lib/active_support/dependencies.rb 118 in `const_missing'
3   /opt/alminium/vendor/plugins/redmine_lightbox/config/routes.rb  1   
4   /opt/alminium/vendor/rails/activesupport/lib/active_support/dependencies.rb 173 in`load_without_new_constant_marking'
5   /opt/alminium/vendor/rails/activesupport/lib/active_support/dependencies.rb 173 in `load'
6   /opt/alminium/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb    287 in`load_routes!'
7   /opt/alminium/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb    287 in `each'
8   /opt/alminium/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb    287 in`load_routes!'
9   /opt/alminium/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb    267 in `reload!'
10  /opt/alminium/vendor/rails/railties/lib/initializer.rb  537 in`initialize_routing'
11  /opt/alminium/vendor/rails/railties/lib/initializer.rb  188 in `process'
12  /opt/alminium/vendor/rails/railties/lib/initializer.rb  113 in`send'
13  /opt/alminium/vendor/rails/railties/lib/initializer.rb  113 in `run'
14  /opt/alminium/config/environment.rb 24  
15  /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb  31  in`gem_original_require'
16  /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb  31  in `require'
17  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb 222 in`preload_application'
18  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb 181 in `initialize_server'
19  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/utils.rb 572 in`report_app_init_status'
20  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb 174 in `initialize_server'
21  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb   204 in`start_synchronously'
22  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb   180 in `start'
23  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb 149 in`start'
24  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb 219 in `spawn_rails_application'
25  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server_collection.rb    132 in`lookup_or_add'
26  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb 214 in `spawn_rails_application'
27  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server_collection.rb    82  in`synchronize'
28  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server_collection.rb    79  in `synchronize'
29  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb 213 in`spawn_rails_application'
30  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb 132 in `spawn_application'
31  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb 275 in`handle_spawn_application'
32  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb   357 in `__send__'
33  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb   357 in`server_main_loop'
34  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb   206 in `start_synchronously'
35  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/helper-scripts/passenger-spawn-server  99  

●構築時メッセージ（2回目のsmelt）

下記が犯人と思います。
「
rake aborted!
uninitialized constant RedmineApp
」

以下、2回目構築のyy選択後部分。

Starting mysqld:                                           [  OK  ]
ERROR 1007 (HY000) at line 1: Can't create database 'alminium'; database exists
y
~/alminium ~/alminium
rake aborted!
uninitialized constant RedmineApp

Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
rake aborted!
uninitialized constant RedmineApp

Tasks: TOP => redmine:load_default_data => environment
(See full trace by running task with --trace)
~/alminium
Already on 'master'
Already on 'master'
Already on 'master'
HEAD is now at f3fef0d... Merge pull request #475 from alminium/7e1f828dec6
Already on 'backlogs-support'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
Already on 'master'
~/alminium ~/alminium
rake aborted!
uninitialized constant RedmineApp

Tasks: TOP => db:migrate_plugins => environment
(See full trace by running task with --trace)
rake aborted!
uninitialized constant RedmineApp

Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
rake aborted!
uninitialized constant RedmineApp

Tasks: TOP => db:migrate:upgrade_plugin_migrations => environment
(See full trace by running task with --trace)
rake aborted!
uninitialized constant RedmineApp

Tasks: TOP => redmine:backlogs:install => environment
(See full trace by running task with --trace)
~/alminium
grep: /etc/selinux/config: No such file or directory
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]

**Comment by drakontia** [comment]
どのタイミングで実行したかによりますが、redmine_lightboxの最新版がRedmine 2.0.xしか対応しなくなったので、その関係で失敗したのかもしれません。
Redmine 1.3対応のものをダウンロードしてくるようにALMiniumを変更したので、最新版にした上でもう一度実行して頂けますか。なお、実行前にはuninstallスクリプトでデータベースや設定を削除してください。

**Comment by bomber555** [comment]
早急なご対応ありがとうございます。
問題が再現せず、画面の表示まで確認できました。

下記、AmazonEC2上で動作確認取れましたので、
動作環境に加えていただけましたら幸いです。

MyAMIs: Amazon Linux AMI 2012.03 64bit
uname -a: Linux ip-10-162-19-248 3.2.12-3.2.4.amzn1.x86_64 #1 SMP Thu Mar 22 08:00:08 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

CommunityAMIs: ami-3cfc4b3d ebs 324077455750/centos-6-i386-ebs-beta2.img
uname -a: Linux ip-10-160-49-96 2.6.32-71.29.1.el6.i686 #1 SMP Mon Jun 27 18:07:00 BST 2011 i686 i686 i386 GNU/Linux

ご対応ありがとうございます。

P.S.
はじめての本格環境なので楽しみにしております！
