### ISSUE TITLE
v2.0.0 ユーザーの管理でエラーになる

### ISSUE THREAD

**Issue by shabutora** [alminium/alminium#52]
管理画面のユーザーを選択すると、Internal Server Errorになる。

CentOS6.3

ログは以下の通り。

Started GET "/users/3/edit" for 172.16.4.29 at 2012-07-12 18:16:21 +0900
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"3"}
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from _app_views_users_edit_html_erb___1654524549625790073_66592440 at /opt/alminium/app/views/users/edit.html.erb:4)
  Rendered users/_mail_notifications.html.erb (111.7ms)
  Rendered users/_preferences.html.erb (10.4ms)
  Rendered users/_form.html.erb (133.5ms)
  Rendered users/_general.html.erb (135.6ms)
  Rendered users/_memberships.html.erb (3.0ms)
  Rendered common/_tabs.html.erb (145.7ms)
  Rendered users/edit.html.erb within layouts/admin (150.8ms)
Completed 500 Internal Server Error in 158ms

ActionView::Template::Error (Missing partial users/avatar with {:locale=>[:ja, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb, :rjs]}. Searched in:
- "/opt/alminium/plugins/redmine_xls_export/app/views"
- "/opt/alminium/plugins/redmine_spent_time_column/app/views"
- "/opt/alminium/plugins/redmine_scm/app/views"
- "/opt/alminium/plugins/redmine_lightbox/app/views"
- "/opt/alminium/plugins/redmine_backlogs/app/views"
- "/opt/alminium/app/views"
  ):
  21: </script>
  22: 
  23: <% tabs.each do |tab| -%>
  24:   <%= content_tag('div', render(:partial => tab[:partial], :locals => {:tab => tab} ),
  25:                        :id => "tab-content-#{tab[:name]}",
  26:                        :style => (tab[:name] != selected_tab ? 'display:none' : nil),
  27:                        :class => 'tab-content') %>
  app/views/common/_tabs.html.erb:24:in `block in _app_views_common__tabs_html_erb___44025519035258087_68256180'
  app/views/common/_tabs.html.erb:23:in`each'
  app/views/common/_tabs.html.erb:23:in `_app_views_common__tabs_html_erb___44025519035258087_68256180'
  app/helpers/application_helper.rb:231:in`render_tabs'
  app/views/users/edit.html.erb:9:in `_app_views_users_edit_html_erb___1654524549625790073_66592440'

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

CentOS 6.3はまだ動作確認できておりません。時間があるときに調べてみます。

よろしくお願いします。

**Comment by mikoto20000** [comment]
不具合を確認しました。取り急ぎご連絡まで。

**Comment by angelndxp** [comment]
このエラーは、現在のAmazon Linuxをベースにした場合においても同じ症状が出ました。

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。この問題はRedmine Local Avatarsプラグインの不具合です。

/opt/alminium/plugins/redmine_local_avatars

を削除後、Apacheを再起動すれば問題は解決すると思います。(ローカルアバターは使えなくなってしまいますが)

よろしくお願いします。

**Comment by angelndxp** [comment]
redmine_local_avatars
を無効にすることにより、無事不具合が直りました。(Amazon Linux 上で確認)
(バックアップディレクトリ作って、このディレクトリごと待避してみただけですが・・・)

これは、 redmine_local_avatars 本家の改修待ち、ってことになりそうですね。
改修まで、2.0からこのプラグインを抜くとか。

**Comment by mikoto20000** [comment]
本家では開発がとまっているので、ALMiniumプロジェクトでフォークしてメンテナンスしています。

少しだけまともに動くように直してみたので、よろしければ試してみてください。

https://github.com/alminium/redmine_local_avatars

からredmine-2.0.xブランチをお使いください。
- ユーザ設定画面のエラーをなくした
- 個人設定からアバターを設定できるようにした

あたりが改善されています。制限としてはユーザ設定画面からアバターの設定はエラーになります。
よろしくお願いします。

**Comment by shabutora** [comment]
確認できました。
ありがとうございます。
