### ISSUE TITLE
自動メール設定追加の提案

### ISSUE THREAD

**Issue by angelndxp** [alminium/alminium#53]
現在、ALMiniumのセットアップにはシステムメールを出すためのLinux側メール設定が自動で出来ません。
ALMiniumを使おうという人の中には、メール設定をすることが困難な人もいるかもしれません。
そこで、AWS-ALMiniumでは、EC2単体インストール版にメール設定をG-meilを使うことを前提に自動化するスクリプトを作りました。
ALMinium側でメールの設定を自動化する仕組みを入れる計画などはありますか？

**Comment by mikoto20000** [comment]
ご提案ありがとうございます。入れたいと思っていましたが、今まで手つかずでいました。

もしよろしければ、変更点をプルリクエストをお送り頂ければ修正を取り込みたいと思います。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
masterにマージしたのでクローズします。
