### ISSUE TITLE
環境変数のデフォルト値の採用

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#54]
AWS-ALMiniumにて、スクリプトを書き換えてプロンプトレスを実現しているが、環境変数にあらかじめ値が設定されていれば、readによる環境変数の読み込みをスキップするように変更すれば、スクリプトの書き換えが不要になる。

**Comment by angelndxp** [comment]
AWS-ALMiniumでのホスト名指定の変数は、「ALMHOSTNAME」としています。
read HOSTNAME 部分を書き換えずにスキップした場合、他で$HOSTNAMEを使っていると、そこが「環境変数」となり、ALMHOSTNAMEと値が異なってこないか心配です。

HOSTNAME環境変数は、クラウドでは基本的に「起動するたびに変化する」ものです。
また、AWSの場合、HOSTNAMEと実際にアクセスするDNS公開アドレスがもともと異なるため、「アクセスしたいURL(独自ドメイン)でホスト名を指定する」ことが必要になるのです。HTTPSやるときは特に重要。
固定IPを割り振ると、またそこにも公開用DNS指定用アドレスがついてきます。この公開用アドレスをCNAMEのVALUE値に指定することで、独自ドメインでのアクセスを実現します。
さらに、HTTPSをする時のssl.confの記述にも影響を与え、Gitでうまくリポジトリを引っ張れなくなることもあります。ロードバランサーを使ってSSL付きでオートスケールを組もうと思ったら、HOSTNAME環境変数基準でシステムを組むと確実に無茶苦茶になります。

HOSTNAMEは環境変数を使うのではなく、「指定必須、使いたいURLで書く」のが、クラウドの特性に左右されない一番良い方法です。変数を環境変数と被らないようにしたのも意図的なもので、AWS-ALMiniumでは、こうしたクラウドの特性を踏まえた作り方をしています。

いっそのこと、AWS-ALMinium側のホストネーム指定の変数をHOSTNAMEとすれば、これ解決しそうですか？

**Comment by mikoto20000** [comment]
コメントありがとうございます。

HOSTNAMEの設定は、ALM_HOSTNAMEとやっているので大丈夫です。詳細はこちらをご覧ください。

https://github.com/alminium/alminium/commit/95f60e0efda41c550f1335e09a7b7d26e037be32
