### ISSUE TITLE
SSLを有効にしているとき、証明書検証を無効にしてもGitが使えない

### ISSUE THREAD

**Issue by angelndxp** [alminium/alminium#55]
AWS-ALMiniumをテストしている際に気づいて、AWS-ALMinium HTTPS版では一時避難的にバグをfixする対策をしてありますが、できれば本家にバグ修正を取り込んでいただきたいと思っています。

　ssl.confにServerNameが記述されないことが原因であることまでは判明しているので、fixを作成しようと思っています。

　ただ一つ問題がありまして、Amazon Linuxベースで作業しているので、RHEL6の修正場所はわかるのですが、他のOSについてはさっぱりです。RHEL6に修正を入れておくので、他のOSについてはお任せします。

**Comment by mikoto20000** [comment]
CentOS 6.xはServerNameが記載されなくてもSSLが利用できるのですが、Amazon LinuxはSSLのホスト名検証が有効になっているということでしょうか?

だとすると、Gitだけでなく、ALMiniumのWebサイト自身も見れないという状況になりそうな気がします。

取り急ぎ、
1. Gitだけなのか、ALMinium本体のWebサイト含めてNGなのか?
2. CentOSでも同様の現象が発生するのか(手元ではきちんと動いているので)

をお教えいただけるとありがたいです。

ちなみにUbuntuに関してはホスト名の検証が有効なのは分かっていたので、最初から対応しています。

よろしくお願いします。

**Comment by angelndxp** [comment]
再検証して根本原因判明。
　現象としては、Webはエラーが出るがアクセス可能、Gitは壊滅です。Amazon Linux、CentOS6.2両方で出ます。
　おそらくそちらで動いている環境とこちらの環境が異なっている可能性が高いです。

　原因は、 /etc/hosts にサーバー名がないこと。
　
127.0.0.1   localhost localhost.localdomain

としか書かれていない場合、https://example.hogehge.comでアクセスするとエラーになります。

　ここに、アクセスするFDQNを入れると、アクセスが可能になります。

　ローカルで運用している場合、初期設定で /etc/hosts の設定の中にサーバー名を入れませんでしたか？
　ローカルインストールしてアクセスしている状況が

ホスト名：server
URL：https://server/git/test
証明書サーバー名：server

というような一致とかないでしょうか？

　証明書のターゲットURLはテキトーでもいいのですが、URLと/etc/hostsは必ず一致する必要があります。

　この場合、ssl.confにアクセスするURLでServerNameを書いてしまったほうがいいと思います。クラウドだと変動IPを基本とするので、hostsで対応するのは避けたほうが望ましい。

　ここにもハマった人がいるようです。
http://www.roppi.net/2011/12/install_alminium/

> ちなみにUbuntuに関してはホスト名の検証が有効なのは分かっていたので、最初から対応しています。
> 　これが、redmine.confに書かれているServerName %HOSTNAME%のことなのであれば、インストーラーの最初のURLを引っ張ってきて同じように対応すればいいのでは？

　証明書もHOSTNAMEベースで作られていたので、できれば最初に指定するホスト名(URL)で証明書を作ったほうが望ましいと思います。証明書のターゲットURLとアクセスURLが異なることも、(今回の場合は関係ないですが)トラブルの元になりやすいので。検証するときの項目も増えるし・・・

**Comment by mikoto20000** [comment]
インストールしたホストではなく、他のホストからならアクセスできませんか?
- 基本的にALMinium自身をインストールしたホストからアクセスすることはありません(必要ならhttpでアクセス可能です)
- ホスト名を設定してしまうと、後でIPを変えたりDNSに登録したときに、登録した名前以外のアクセスができない

という理由で、ホストは設定していません(というのを検証して思い出しました)。

上記の理由でホスト名は現状のまま無設定にしたいと思いますが、如何でしょうか?

よろしくお願いします。(他のホストからアクセスできない場合は、この限りではありませんが)

**Comment by angelndxp** [comment]
インストールしたのはクラウド上のサーバーで、そのホスト(インスタンス)からはアクセスすることはありません。基本的に、個人のWindows(TortoiseGit) or MacOS(Source Tree)より、証明書検証を無効状態にしてアクセスしています。

　厳密にテストするため、以下の様な条件を設定しました。
・FireWallはHTTPS(443)しか開放せず、HTTP(80)は閉じたまま。(HTTPリダイレクト不可能な状態)
＜テスト＞
条件1. 証明書は、デフォルトの状態と、alminium.example.com(アクセスするURL)で作り直し、CNAMEで書いてサーバーに向いている状態を手動で設定したものを作る。
条件2. /etc/hosts の記述を確認 (デフォルトは 
127.0.0.1 localhost localhost.localdomain の記述のみ)
1. 条件1がオリジナル、条件2がデフォルト → アクセス出来ない
2. 条件1が手動設定、条件2がデフォルト → アクセス出来ない
3. 条件1がオリジナル、条件2がホスト記述追加 → アクセスできる
4. 条件1が手動設定、条件2がホスト記述追加 → アクセスできる
- おまけ. ssl.confにServerNameを書く → 上記4条件全てでアクセス可能

　という結果が得られています。ここから /etc/hosts 記述と見るのが妥当でしょう。
　(ちなみに、AzureのCentOSでHTTPSセットしようと思ったら、apacheの起動エラーが出ます。必ずServerNameを設定するか、/etc/hosts にホスト名を書かないと、名前解決できないエラーになりapacheが動かないというアホなことになります)

　ただ、/etc/hosts の記述はクラウドを運用するときは「IP変動前提であまり触らない」ほうがよいので、ssl.conf記載方式で良いかと思います。

　それに、開発はじめて仲間にURL広めたら、なかなか変更することはないと思います。サーバー乗り換え(＝再インストール)でもしない限り。だったら、HTTPS使うときは「指定したURLで縛ってしまいます」と言い切ってもいいのでは？

**Comment by mikoto20000** [comment]
> 証明書検証を無効状態にしてアクセスしています。

```
$ git config --global http.sslverify false
```

に設定しているということでよろしいですか?

> 条件1がオリジナル、条件2がデフォルト → アクセス出来ない

これおかしいですね。VirtualBoxにCentOS 6.3(x64)を入れた環境ではアクセス
できています。どうしてアクセスできないのかが謎です。AmazonのCentOSは
何か設定変更が施されているのでしょうか。

> ここから /etc/hosts 記述と見るのが妥当でしょう。

こちらの環境で何か記述しているという意味でしょうか? 何も追加していないです。

> 　(ちなみに、AzureのCentOSでHTTPSセットしようと思ったら、apacheの起動エラーが出ます。
> 必ずServerNameを設定するか、/etc/hosts にホスト名を書かないと、名前解決できないエラー
> になりapacheが動かないというアホなことになります)

設定がデフォルトのCentOSから変わっているということでしょうか。

現状CentOSで動作しているので、あまりいじりたくはないのですが、時間があるときにAmazonで試してみたいと思います。

ちなみに、私はIPアドレスを指定したURL(https://192.168.1.5/git/testなど)で試しています。IPと名前で異なったりするのでしょうか...

**Comment by angelndxp** [comment]
証明書検証の無効はご指摘のとおりです。

　IPアドレス指定でのアクセスを試してみたところ、何も書いてなくてもアクセスできました。(AWSの同一セキュリティーグループからテスト) そちらでうまく動いているのは、URLアクセスになっていない、というのが理由となると思います。IPアドレスの場合「ホスト名の解決」の概念が吹っ飛ぶので、/etc/hostsは無視されます。この挙動の違いが出ているものと思われます。

　イントラで使う場合はIPアドレスアクセスになることもあると思いますが、殆どの場合DNSにホストを指定(Aレコード or CNAMEレコード)して、名前でアクセスするのが主流となると思います。さらにクラウドとなると、直IPアドレスでアクセスはまずしません。実際に使う名前アクセスを想定した検証が必要でしょう。(今回のように)

　ちなみに、CentOS実験をやったのは、AWSではなくWindows Azureです。AWSでは、Amazon LinuxがCentOSのような役割を担っているので、RHELしか提供されていません。(正確には、Amazon LinuxはFedoraに近いですが)

**Comment by mikoto20000** [comment]
やっと動作しない理由が分かりました。こちらの環境では動作していたので、不思議に思っていました。ありがとうございます。

devブランチで修正しましたので、よろしければ試してみてください。

よろしくお願いいたします。

**Comment by angelndxp** [comment]
devブランチで確認し、問題なくアクセスできました。
　リリースする際は、AWS-ALMiniumのHTTPS版にも影響するのでお知らせください。

　もう1点、自動で作成される証明書のホスト名が、$HOSTNAME ベースになっているのですが、これがあるとブラウザの証明書のエラーに「URLと一致しません」と出ます。利用上は問題ありませんが、GitでURL縛りをする処理を今回行ったので、自動で作成する証明書も同じようにURLでアクセスする前提のサーバー名になりませんか？

**Comment by mikoto20000** [comment]
今週末辺りにmasterへマージします。watchの設定をしていれば変更をメールで受け取ることができると思いますので、そちらでご確認ください。

あと、証明書のURLエラーの件については、このIssueとは別の問題ですので、新たにIssueを起こしました。 https://github.com/alminium/alminium/issues/57

よろしくお願いいたします。
