### ISSUE TITLE
ubuntu12.04(Amazon版)で動作しない

### ISSUE THREAD

**Issue by angelndxp** [alminium/alminium#59]
コマンド4つでインストールしてみたところ、Webページに以下のように表示され、ALMiniumの画面が出てきません。

It works!

This is the default web page for this server.

The web server software is running but no content has been added, yet.

**Comment by mikoto20000** [comment]
Ubuntuはx86版でしょうか、x64版でしょうか?
x64版だとサポートしていないので確実に動かないと思います。

x64版であれば、mod_passengerの設定がうまく行っていない可能性があります。
Apacheのredmineの設定ファイルがきちんと設定されているかどうか確認
頂けるとありがたいです。

**Comment by mikoto20000** [comment]
masterブランチで下記の条件で動作確認しました。
- Ubuntu Server 12.04.1を利用(Desktop版は試験対象に含まれていません)
- インストール時にMySQLのrootパスワードを何度か聞いてくるが空にする

以上、よろしくお願いいたします。

**Comment by angelndxp** [comment]
Amazonのubuntu x64をベースに、上記確認事項を元にAmazonでのインストールを試してみたところ、Apacheの起動段階でSyntaxエラーとなり動作しません。

---
- The apache2 configtest failed, so we are trying to kill it manually. This is almost certainly suboptimal, so please make sure your system is working as you'd expect now!
  ... waiting                                                             [ OK ]
- Starting web server apache2                                                  Syntax error on line 6 of /etc/apache2/sites-enabled/redmine:
  ServerName takes one argument, The hostname and port of the server
  Action 'start' failed.
  The Apache error log may have more information.
                                                                       [fail]
  ----------------------------------------------------------------------------------------------------------------------------

　追記：x86をベースにしても同じ現象が起こることを確認しました。

**Comment by mikoto20000** [comment]
Syntax error on line 6 of /etc/apache2/sites-enabled/redmine の6行目はどうなっているでしょうか?

ひょっとしてホスト名を空にしてインストールしていませんか?

**Comment by angelndxp** [comment]
このエラーの影響が、「ホスト名を空にしてインストールしたこと」が原因であることがわかりました。
