### ISSUE TITLE
インストールが途中で止まる

### ISSUE THREAD

**Issue by nouphet** [alminium/alminium#62]
CentOS 6.2 でインストールしたが、下記の箇所でインストールが止まります。
2度試してみて同様の結果でしたので、issueを挙げさせてさせて頂きます。

```
Initialized empty Git repository in /usr/local/src/alminium/cache/redmine_spent_time_column/.git/
remote: Counting objects: 397, done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 397 (delta 275), reused 365 (delta 243)
Receiving objects: 100% (397/397), 30.69 KiB | 15 KiB/s, done.
Resolving deltas: 100% (275/275), done.
Branch backlogs-support set up to track remote branch backlogs-support from origin.
Switched to a new branch 'backlogs-support'
```

下記にてプロセスをkillすると後続処理が走ったが、redmine-plugin のインストールは完了していない様子。

```
# ps -ef |grep http
root     11389  5627  0 15:00 pts/0    00:00:00 svn co http://svn.s-andy.com/scm-creator/ cache/redmine_scm
root     11709 11582  0 15:54 pts/1    00:00:00 grep http
# kill -9 11389
```

後続処理

```

^C^C^Cinst-script/redmine-plugins: line 16: 11389 強制終了            svn co ${URL_NAME[$i]} cache/${DEST_NAME[$i]}
Initialized empty Git repository in /usr/local/src/alminium/cache/redmine_redcarpet_formatter/.git/
remote: Counting objects: 259, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 259 (delta 91), reused 216 (delta 48)
Receiving objects: 100% (259/259), 43.29 KiB, done.
Resolving deltas: 100% (91/91), done.
.
.
.
.
```

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

下記のコマンドを手で打つとどうなるでしょうか?

```
$ svn co http://svn.s-andy.com/scm-creator/ cache/redmine_scm
```

こちらでも確認してみますが、一時的に上記のサイトがダウンしたために失敗しているように思います。もしくは、プロキシが必要な環境で実行しているのですが、プロキシの設定が正しくされていないためでしょうか、、、

よろしくお願いします。

**Comment by nouphet** [comment]
対応方法の提示、ありがとうございます。
提示頂いたコマンドを実行してみたのですが、何も反応がない状態です。

backlogs-supportは使わない予定ですので、取り急ぎ使えるようにしたいのですが

・backlogs-supportをインストールしないで alminium をインストールを行う方法

or

・実績のあるバージョンをご提示いただく

をお願いしたいです。

**Comment by mikoto20000** [comment]
上記のsvnで止まるということは、redmine_scm(Redmineからリポジトリ作成するプラグイン)のインストールで停止しているということです。プロキシがない環境・プロキシがある環境で動作実績はあるので、環境の問題だと思います。

幾つか確認したいのですが、
1. プロキシが必要な環境でしょうか?
2. その場合http_proxy,https_proxy環境変数は設定していますでしょうか?
3. redmine_scmで止まったときにプロキシのユーザ名/パスワードを聞いてきませんか?

また、インストール方法はALMiniumのトップページに書いてありますが、これに従っているでしょうか?

https://github.com/alminium/alminium

よろしくお願いします。

**Comment by nouphet** [comment]
プロキシは不要な環境です。
でもルータのファイアウォールで80番、443番、sshポート（22番ではない）のみ開いている状態です。
使えるポートに制限があると支障があるのでしょうか…。

インストールはALMiniumのトップページに記載の手順に従って行なっています。

**Comment by nouphet** [comment]
下記コマンドを別の環境（ローカルのmac）で実行したら正常にいけました。

```
$ svn co http://svn.s-andy.com/scm-creator/ cache/redmine_scm
```

やはりネットワークの環境によるものだと思われます。
F/Wをいったんフルオープンにしてもう一度チャレンジしてみます。

**Comment by nouphet** [comment]
・ルータのF/Wをoff
・CentOSのF/W（iptables）をoff

としてみましたが、状況は変わりませんでした。

**Comment by nouphet** [comment]
> redmine_scmで止まったときにプロキシのユーザ名/パスワードを聞いてきませんか?

これについては何も反応がなく、何も聞いてこないです。

**Comment by nouphet** [comment]
たびたびすみません。

AWS上では問題なくインストールが完了しましたので、
再度エラーになった環境でインストールしてみました。
下記の部分（問題の部分）でタイムアウトになり、以降の処理へ進みましたので、インストールは完了まで行きましたが、プロジェクト作成時にSCMが選べない状態です。（当然といえば当然ですが）

> Branch backlogs-support set up to track remote branch backlogs-support from origin.
> Switched to a new branch 'backlogs-support'
> svn: REPORT (URL: '/scm-creator/!svn/vcc/default'): サーバからの応答を待っているうちにタイムアウトしました (http://svn.s-andy.com)

gitとの連動をさせたいのですが、 backlogs-support を別途有効化（インストール）してRedmineとgitを連動させるにはどうしたら良いでしょうか？
ご教示頂けますと大変嬉しいです。

ちなみに本件の様な質問を書き込むのが、この場所で適切なのかがちょっと気になっています。
もし他に質疑応答用のフォーラムなどがありましたら、今後はそちらに書き込むようにしますので教えて頂けると幸いです。

**Comment by mikoto20000** [comment]
環境の問題のようなので、ひとまずクローズさせて頂きます。

> gitとの連動をさせたいのですが、 backlogs-support を別途有効化（インストール）して
> Redmineとgitを連動させるにはどうしたら良いでしょうか？

通常のRedmineのプラグインのインストール手順でインストールしてください。ベースはRedmineなので、Redmineと同じです。

> ちなみに本件の様な質問を書き込むのが、この場所で適切なのかがちょっと気になっています。

今のところ、GitHubしかないのでここで結構です。

よろしくお願いします。
