### ISSUE TITLE
httpプロキシ経由のインストールすると、SCM_Creatorがインストールされない。

### ISSUE THREAD

**Issue by moguno** [alminium/alminium#63]
CentOS 6.3 minimalクリーンインストールにて。

プロキシサーバ経由（環境変数http_proxy、https_proxy）でインストールした場合、インストーラは完走しますが、リポジトリの作成時にgitリポジトリが作成されない事象が発生しました。

原因はSCM_Creatorのインストール時にsvnがプロキシサーバを見ておらず、名前解決に失敗していたためでした。
~/.subversion/serversにプロキシの設定を書いて対処しました。

本ファイルをインストーラが書き換えるのはマズイと思いますので、警告を表示等できないでしょうか。
せめて、インストーラが失敗するようにして頂けると助かります。

以上、ご検討下さい。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

ユーザ名・パスワードを途中で聞かれて、そこにプロキシのユーザ名・パスワードを入れると正しくインストールできませんか?
私はプロキシ環境課ではいつもそうしています。

ただ、警告メッセージはあった方がいいですね。検討します。

**Comment by moguno** [comment]
返信有難う御座います。
こちらではパスワードは聞かれませんでした。
以下の様に、svnがプロキシ設定を解して無いように思えます。

[root@ALMinium alminium]# export | grep proxy
declare -x http_proxy="http://hoge:9515"
declare -x https_proxy="https://hoge:9515"

[root@ALMinium alminium]# svn co http://svn.s-andy.com/scm-creator/ cache/redmine_scm
svn: OPTIONS (URL: 'http://svn.s-andy.com/scm-creator'): Could not resolve hostname `svn.s-andy.com': Host not found (http://svn.s-andy.com)

同URLに対するwgetは正常
[root@ALMinium alminium]# wget http://svn.s-andy.com/scm-creator/
--2012-09-19 03:00:02--  http://svn.s-andy.com/scm-creator/
hogeをDNSに問いあわせています... 10.160.128.1
hoge|10.160.128.1|:9515 に接続しています... 接続しました。
Proxy による接続要求を送信しました、応答を待っています... 200 OK
長さ: 519 [text/html]
`index.html' に保存中

100%[========================================================================================================================================================================>] 519         --.-K/s 時間 0s

2012-09-19 03:00:02 (40.3 MB/s) - `index.html' へ保存完了 [519/519]

[root@ALMinium alminium]# svn --version
svn, バージョン 1.6.11 (r934486)
   コンパイル日時: Jun 23 2012, 00:44:03

**Comment by mikoto20000** [comment]
ALMiniumのフォークを利用しているため、最新版では問題はおきなくなりました。
