### ISSUE TITLE
backlogs プラグインの影響で(?)チケットの期日が変更できなくなる問題が起きています

### ISSUE THREAD

**Issue by yos-tanita** [alminium/alminium#66]
CentOS6.3 に redmine2.0.3ベースのALMiniumをインストールしたところ、
チケットの期日が変更できない、という問題が発生しました。

具体的には
- プロジェクトを作成する
- プロジェクトにバージョンを設定する
- "機能"トラッカーのチケットを作成し、そのチケットにバージョン設定する
- すると、そのチケットの期日が強制的にバージョンの期日に固定されて変更できなくなる
- "バグ"や"タスク"のトラッカーのチケットではこの現象は発生しない
- オリジナルの redmine2 ではこの現象は起きないので、組み込まれたプラグインの影響と考え、一つずつプラグインをアンインストールしていき、 redmine bucklogs plugin をアンインストールした時点で問題が発生しなくなりました。
- なお、backlogs プラグインを使う予定は無くて、問題が発生した時はそのプロジェクトの"バックログ”モジュールは無効状態でした。

以上。

**Comment by mikoto20000** [comment]
詳細なご報告ありがとうございます。

最新のbacklogsで試してみたところ、問題は発生していないようなので次に
backlogsをバージョンアップするタイミングで修正したいと思います。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
2.2.2では修正されていると思います。
