### ISSUE TITLE
インストールで失敗するようになりました

### ISSUE THREAD

**Issue by tnebu1999master** [alminium/alminium#67]
先日まではインストールうまくいってましたが、昨日からインストールが
うまくいきません。インストール後に、URL開いてもNOT FOUNDとなります。

VPSでCentOSの環境です。

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat `cache/redmine-2.0.3/*': No such file or directory
cp: cannot create regular file`/opt/alminium/config/': Is a directory
cp: cannot create regular file `/opt/alminium/config/': Is a directory

インストール途中でこのようなエラーでてます。
Linuxぜんぜん分からずですみません。

**Comment by mikoto20000** [comment]
RubyForgeが落ちているとALMiniumはインストールできません。昨日はRubyForgeが終日落ちていたと思います。http://www.rubyforge.org/にアクセスしてRubyForgeが動作しているかどうか確認してからインストールしてみてください。
