### ISSUE TITLE
svnでコミット後に post-commit hook failed (exit code 8) with no output. がでる

### ISSUE THREAD

**Issue by singkamuy** [alminium/alminium#68]
お世話になります。
昨日Amazon Linux 64bit にて環境構築を致しました。
コミット時に「post-commit hook failed (exit code 8) with no output.」のwarningが表示されているのですが、解消方法をどなたかご教授いただけませんでしょうか。

/opt/alminium/hooks/svn の post-commit にはapacheで実行権限はついております。

よろしくお願い致します。

**Comment by mikoto20000** [comment]
本件解決しましたでしょうか?

問題が再現しないので一旦クローズします。最新版を試して再現するようならまたレポート頂けると幸いです。

**Comment by singkamuy** [comment]
お世話になっております。
本現象ですが、未だに解決できておりません。
教えていただきました最新版で検証したいと思います。
以上よろしくお願い致します。

**Comment by ucho** [comment]
最新版でなくて申し訳ないのですが、1/31時点でのmasterで同様の現象が再現しました。

途中まで原因を解析し、警告の発生する流れだけは把握できましたので、一応ご報告しておきます。  
- SVNのコミットフックでpost-commitスクリプトが実行される
- post-commitスクリプトはALminiumの bin/alm-sync-scm を実行する
- alm-sync-scmではwgetでRedmineのsys/fetch_changesetsにアクセスする
- fetch_changesetsが404エラーを返すため、wgetが[終了ステータス8](http://www.gnu.org/software/wget/manual/html_node/Exit-Status.html)で終了する
- 実行パスを遡って、SVNクライアントに"exit code 8"の警告が表示される

（原因そのものはわかっていません。すみません）

**Comment by ayapapa** [comment]
今更ですが、自分も嵌ったので、ログのため記載させていただきます。
/opt/alminium/bin/alm-sync-scm
のwgetコマンドのオプションで--no-proxyを指定したら、解決しました。
プロキシーが邪魔をしていたのだと思います。
もう一つの原因（RedmineにおけるリポジトリのAPIキー設定）も確認できました。こちらは、キーを削除（空に）して解決。
参考：https://github.com/ayapapa/alminium/issues/8
