### ISSUE TITLE
Backlogsプラグインの設定を更新しても反映されない

### ISSUE THREAD

**Issue by soappp** [alminium/alminium#69]
先日、CentOS 6.3 64bit版の環境を新規に作成し、ALMiniumのインストールを行いました。
特にエラーもなくインストールが完了し、概ね動いておりますが、Backlogsプラグインの設定が更新できないようです。

2台のマシンにインストールしましたが、どちらでも同じ事象が発生しました。

回避方法も見つかりましたので、併せてご報告いたします。
### 環境
- OS: CentOS 6.3 64bit版
- ALMiniumのブランチ: master
- Backlogs プラグインのバージョン: Backlogs version v0.9.26 (645d6198887e0ff568818b19ba5ceda538dcf713), Redmine version 2.0.3.stable
### 再現手順
1. VMwareで新規VMを作成し、CentOS 6.3 64bit版をデフォルト設定でインストール
2. ALMiniumをデフォルト設定でインストール
3. [管理]-[プラグイン]-[Redmine Backlogs]-[設定] で Backlogs プラグインの設定画面を表示
4. 適当に設定を変更し、[適用]
   
   →「更新しました。」と表示されるも、変更する前の設定が表示される。見た目だけでなく、実際の設定も変わっていない。
### 発生要因と回避方法

どういうわけか、DB上に Backlogs プラグインの設定を保持するレコードが2件存在しておりました。

```
mysql> select count(*) from settings where name='plugin_redmine_backlogs';
+----------+
| count(*) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)
```

id=1とid=2がありましたが、id=2のほうを手動で削除したところ、問題なく Backlogs の設定が変更できるようになりました。ご参考まで。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

よろしければ、redmine-2.1.xブランチで試してみて頂けますか?

治っていると思います。

※ 利用するRedmineは2.2.0になって、若干テストができていないところがありますが、、、

**Comment by soappp** [comment]
コメントありがとうございます。

新しいVMを作成し、redmine-2.1.x ブランチでALMiniumをインストールしてみましたが、報告させていただいた問題は解消せず再現いたしました。報告内容の「発生要因と回避方法」につきましても、masterブランチのときと同様の状況になっております。

Backlogs プラグインのバージョンは次のとおりです。

Backlogs version v0.9.28 (300ede8cfb5d88d346c0248109875a135cab7463), Redmine version You are running backlogs v0.9.28, latest version is 0.9.27

念のため、[管理]-[情報] の内容もコピペいたします。
Environment:
  Redmine version                          2.2.0.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.9
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_backlogs                         v0.9.28
  redmine_charts                           0.2.0
  redmine_drafts                           0.2.0
  redmine_git_branch_hook                  0.2.1
  redmine_importer                         1.0
  redmine_inline_attach_screenshot         0.4.2
  redmine_jenkins                          2.1.0
  redmine_local_avatars                    0.0.3-forked
  redmine_plugin_views_revisions           0.0.1
  redmine_redcarpet_formatter              2.0.1
  redmine_scm                              0.4.1
  redmine_spent_time_column                2.0.0-devel
  redmine_xls_export                       0.2.1

**Comment by ucho** [comment]
本日(1/31)時点でのmasterでインストールしたところ、やはり同様の現象が再現しました。
soapppさんの示してくださった回避方法を実施したところ、正常に設定できるようになりました。

Redmineは2.2.2.stable, Backlogsプラグインはv0.9.33でした。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

masterブランチで修正しました。一度レポート頂いていたのにご迷惑をおかけしてすみません。

**Comment by soappp** [comment]
新しいVMを作成し、masterブランチでALMiniumをインストールしたところ、本件が修正されていることを確認できました。
この度はご対応ありがとうございました。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。報告しっぱなしの人が多いので助かります(汗
