### ISSUE TITLE
csvインポート実施時のundefined methodエラーについて

### ISSUE THREAD

**Issue by ma-watanabe** [alminium/alminium#70]
はじめまして、最近Alminiumを利用させていただいているものです。

importerモジュールで、csvインポート実施時に、
observe_fieldメソッドが無いと、はじかれてしまいます。

下記のサイトによると、Rails3からPrototype helper pluginを使うように書かれていたので、
pluginをインストールしてみましたが、変わりませんでした。
http://gregmoreno.wordpress.com/2010/08/24/rails-3-upgrade-part-4-prototype-helpers-and-javascript/
「Remove jQuery」とか書かれている部分はよくわかりませんでしたので、まだ対処してません。

お手数ですが、切り分け方法について、助言をいただけますでしょうか？

以下、エラーログです。

Completed 200 OK in 25ms (Views: 8.3ms | ActiveRecord: 3.4ms)
^[Started POST "/importer/match" for 192.168.0.100 at 2013-01-18 17:46:59 +0900
Processing by ImporterController#match as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"8FMWxIU1KmCA5j78glFTyjt07ZLT7CxpRRfa0IBBsSc=", "project_id"=>"3", "file"=>#<ActionDispatch::Http::UploadedFile:0x00000007f1fd40 @original_filename="import.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"import.csv\"\r\nContent-Type: text/csv\r\n", @tempfile=#<File:/tmp/RackMultipart20130118-1518-11aprzk>>, "encoding"=>"U", "splitter"=>",", "wrapper"=>"\"", "commit"=>"ファイルをアップロード"}
  Current user: admin (id=1)
  Rendered plugins/redmine_importer/app/views/importer/match.html.erb within layouts/base (82.4ms)
Completed 500 Internal Server Error in 243ms

ActionView::Template::Error (undefined method `observe_field' for #<#<Class:0x00000007760aa0>:0x00000007824810>):
    37:     <label><%= check_box_tag "add_versions", true, false %> <%= l('redmine_importer.label_importer_add_versions') %> </label><br/>      
    38:         <label><%= check_box_tag "update_issue", true, false %> <%= l('redmine_importer.label_update_issue') %>
    39:         </label><br/>
    40:         <%= observe_field("update_issue", :function => <<END_OF_STRING
    41: document.getElementById("journal_field").disabled = !element.checked;
    42: document.getElementById("update_other_project").disabled = !element.checked;
    43: document.getElementById("ignore_non_exist").disabled = !element.checked;
  plugins/redmine_importer/app/views/importer/match.html.erb:40:in`block in _plugins_redmine_importer_app_views_importer_match_html_erb___1634837568585450210_60081520'

私の環境は以下となります。
OS:CentOS 6.3 64bit版
Rails:3.2.11
Ruby:1.9.3p327

**Comment by mikoto20000** [comment]
下記のRedmine Importerプラグインが2.2対応になっているようです。

https://github.com/zh/redmine_importer/

このプラグインで動作確認してみて頂けますか?

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
上記のプラグインに入れ替えると動作すると思うのですが如何でしょうか?

問題ないようでしたら、Issueをクローズしたいと思います。

**Comment by ma-watanabe** [comment]
返事が遅くなり、申し訳ございません。
最新のredmine_importerのmasterに差し替えて、
migrate→サーバー再起動→プロジェクトの設定で再度importにチェックして実行しましたところ、
下記のテンプレートエラーが発生いたしました。

  Rendered plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb (7.0ms)
Completed 200 OK in 22ms (Views: 9.1ms | ActiveRecord: 5.6ms)
Started POST "/importer/result" for 192.168.0.100 at 2013-01-27 16:48:51 +0900
Processing by ImporterController#result as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"8FMWxIU1KmCA5j78glFTyjt07ZLT7CxpRRfa0IBBsSc=", "project_id"=>"3", "import_timestamp"=>"2013-01-27 07:48:40", "fields_map"=>{"#"=>"", "\xE3\x83\x97\xE3\x83\xAD\xE3\x82\xB8\xE3\x82\xA7\xE3\x82\xAF\xE3\x83\x88"=>"", "\xE3\x83\x88\xE3\x83\xA9\xE3\x83\x83\xE3\x82\xAB\xE3\x83\xBC"=>"tracker", "\xE8\xA6\xAA\xE3\x83\x81\xE3\x82\xB1\xE3\x83\x83\xE3\x83\x88"=>"", "\xE3\x82\xB9\xE3\x83\x86\xE3\x83\xBC\xE3\x82\xBF\xE3\x82\xB9"=>"status", "\xE5\x84\xAA\xE5\x85\x88\xE5\xBA\xA6"=>"priority", "\xE9\xA1\x8C\xE5\x90\x8D"=>"subject", "\xE4\xBD\x9C\xE6\x88\x90\xE8\x80\x85"=>"author", "\xE6\x8B\x85\xE5\xBD\x93\xE8\x80\x85"=>"assigned_to", "\xE6\x9B\xB4\xE6\x96\xB0\xE6\x97\xA5"=>"", "\xE3\x82\xAB\xE3\x83\x86\xE3\x82\xB4\xE3\x83\xAA"=>"category", "\xE5\xAF\xBE\xE8\xB1\xA1\xE3\x83\x90\xE3\x83\xBC\xE3\x82\xB8\xE3\x83\xA7\xE3\x83\xB3"=>"fixed_version", "\xE9\x96\x8B\xE5\xA7\x8B\xE6\x97\xA5"=>"start_date", "\xE6\x9C\x9F\xE6\x97\xA5"=>"due_date", "\xE4\xBA\x88\xE5\xAE\x9A\xE5\xB7\xA5\xE6\x95\xB0"=>"estimated_hours", "\xE4\xBD\x9C\xE6\xA5\xAD\xE6\x99\x82\xE9\x96\x93\xE3\x81\xAE\xE8\xA8\x98\xE9\x8C\xB2"=>"", "\xE9\x80\xB2\xE6\x8D\x97 %"=>"done_ratio", "\xE4\xBD\x9C\xE6\x88\x90\xE6\x97\xA5"=>"", "\xE9\x96\xA2\xE9\x80\xA3\xE3\x81\x99\xE3\x82\x8B\xE3\x83\x81\xE3\x82\xB1\xE3\x83\x83\xE3\x83\x88"=>"", "\xE3\x82\xB9\xE3\x83\x88\xE3\x83\xBC\xE3\x83\xAA\xE3\x83\xBC\xE3\x83\x9D\xE3\x82\xA4\xE3\x83\xB3\xE3\x83\x88"=>"", "\xE6\xAE\x8B\xE3\x82\x8A\xE6\x99\x82\xE9\x96\x93\xE3\x81\xAB\xE5\x9F\xBA\xE3\x81\xA5\xE3\x81\x8F\xE3\x83\x99\xE3\x83\xAD\xE3\x82\xB7\xE3\x83\x86\xE3\x82\xA3"=>"", "Position"=>"", "\xE6\xAE\x8B\xE3\x82\x8A\xE6\x99\x82\xE9\x96\x93"=>"", "\xE4\xBA\x88\xE5\xAE\x9A\xE5\xB7\xA5\xE6\x95\xB02"=>"予定工数2", "\xE3\x83\x97\xE3\x83\xA9\xE3\x82\xA4\xE3\x83\x99\xE3\x83\xBC\xE3\x83\x88"=>""}, "default_tracker"=>"3", "unique_field"=>"", "send_emails"=>"true", "add_categories"=>"true", "add_versions"=>"true", "commit"=>"送信"}
  Current user: admin (id=1)
  Rendered plugins/redmine_importer/app/views/importer/result.html.erb within layouts/base (15.9ms)
Completed 500 Internal Server Error in 95ms

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    16:     <thead><tr>
    17:         <th>#</th>
    18:         <% @headers.each do |column| %>
    19:           <th><%= column %></th>
    20:         <% end %>
    21:     </tr></thead>
    22:     <tbody>
  activesupport (3.2.11) lib/active_support/core_ext/string/output_safety.rb:135:in `concat'
  activesupport (3.2.11) lib/active_support/core_ext/string/output_safety.rb:135:in`concat'
  actionpack (3.2.11) lib/action_view/buffers.rb:11:in `<<'
  plugins/redmine_importer/app/views/importer/result.html.erb:19:in`block in _plugins_redmine_importer_app_views_importer_result_html_erb___555134656775136099_52742020'
  plugins/redmine_importer/app/views/importer/result.html.erb:18:in `each'
  plugins/redmine_importer/app/views/importer/result.html.erb:18:in`_plugins_redmine_importer_app_views_importer_result_html_erb___555134656775136099_52742020'
  actionpack (3.2.11) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.11) lib/active_support/notifications.rb:125:in`instrument'
  actionpack (3.2.11) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:47:in`block (2 levels) in render_template'
  actionpack (3.2.11) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.11) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'

**Comment by ma-watanabe** [comment]
インポートしたファイルですが、エンコーディングの設定は、UTF-8 LF(UNIX)です。
下記のデータのインポートを実施しました。
#,プロジェクト,トラッカー,親チケット,ステータス,優先度,題名,作成者,担当者,更新日,カテゴリ,対象バージョン,開始日,期日,予定工数,作業時間の記録,進捗 %,作成日,関連するチケット,ストーリーポイント,残り時間に基づくベロシティ,Position,残り時間,予定工数2,プライベート
,RailsによるアジャイルWebアプリケーション開発 第4版,タスク,,新規,通常,15.1 イテレーションJ1：ロケールの選択,Admin Redmine,Admin Redmine,2013/01/27 11:16,,,2013/01/27,,,0,0,2013/01/27 10:34,,,,-650,,0.5,false

**Comment by ma-watanabe** [comment]
インポート時のAlminiumのファイルフォーマットのオプションは、以下となります。
エンコーディング：  UTF-8

フィールド区切り文字：  ,

引用文字：  "

**Comment by ma-watanabe** [comment]
度々で申し訳ございませんが、再度ご助言をお願いいたします。

**Comment by mikoto20000** [comment]
上記のデータで手元で試してみましたが、親チケットが設定されているため依存関係のエラーがでましたが、正しくインポートは動作しているようです。1点確認ですが、最新のmasterに入れ替えたというのは、

```
$ git clone https://github.com/zh/redmine_importer/
```

で取得したプラグインに入れ替えたということでしょうか?

よろしくお願いします。

**Comment by mikoto20000** [comment]
ちなみにUTF8にはBOM付きのエンコーディングとBOMなしのエンコーディングがありますが、BOMなしのUTF-8で試しました。ファイルがBOM付きのUTF-8ということはないでしょうか?

**Comment by ma-watanabe** [comment]
度々のご回答をありがとうございます。
説明が不足していたのですが、「コラムの対象のフィールド」で、「親チケット」が設定されていると、
下記のエラーが出て、インポート結果が0行で失敗してます。

ー「親チケット」が設定されている場合のエラー
「親チケット」という連携があるコラムをインポートしているので一意な値がある欄を選択が必要です。
ーーーーーーーーーーーーーーーーーーーーーー

その為、「親チケット」を「無視」に設定して、インポートしています。

＞$ git clone https://github.com/zh/redmine_importer/
＞で取得したプラグインに入れ替えたということでしょうか?

下記のmasterを解凍して、redmine_importerにリネームして、入れ替えていました。
wget https://github.com/zh/redmine_importer/archive/master.zip
git cloneでも同様に試しましたが、変わりませんでした。

＞ちなみにUTF8にはBOM付きのエンコーディングとBOMなしのエンコーディングがありますが、BOMなしの
＞UTF-8で試しました。ファイルがBOM付きのUTF-8ということはないでしょうか?

BOM無しのファイルです。
Mac環境で、TextWranglerというエディターで保存しています。
Unix(LF)、Clasic Mac(CR)、Windows(CRLF)でそれぞれ保存しても、
同様にエラーが発生します。

**Comment by mikoto20000** [comment]
ありがとうございます。インストールは問題ないようですね。

問題が再現しないため、これ以上の解析は困難なので、もし差支えなければ、エラーが発生するファイルをmikoto20000 at gmail.com までお送りいただけますか?

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
すいません。原因がわかりました。

https://github.com/mikoto20000/redmine_importer

に修正を反映させましたので、お手数ですが上記のプラグインに差し替えてもう一度試してみて頂けますか?

よろしくお願いいたします。

**Comment by ma-watanabe** [comment]
ありがとうございます！差し替え後、問題無くインポートできるようになりました！
大変助かりました！
今後も愛用させていただきます！

**Comment by mikoto20000** [comment]
ALMiniumで利用しているzhのredmine_importerで下記の通り修正されたのでIssueをクローズします。
- https://github.com/zh/redmine_importer/pull/3

https://github.com/mikoto20000/redmine_importerは不要になったので削除します。
