### ISSUE TITLE
Amazon Linux AMI 2012.09 でJenkinsやGitなどの認証がとおりません

### ISSUE THREAD

**Issue by okahiro** [alminium/alminium#72]
こんにちは。

Aluminiumのセットアップの簡単さが魅力で、使わせていただこうかと思っております。

Amazon Linux AMI 2012.09（64bit）起動後にAlminium（Jenkins込み）をインストールしましたが、Redmineは動作しますが、JenkinsやGitなどへの認証がとおりません。
Redmine上で登録したユーザーでログインしようとしています。

Redmine2.2.2です。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
ご利用ありがとうございます。いくつか確認したいのですが、

1  初期ユーザのユーザadmin/パスワードadminでもアクセスできませんか?
2 Gitはどのようなコマンドを実行したのでしょうか?(コマンドラインですか?)あと、SSLを利用している場合、http.sslverifyをfalseにしているかどうかご確認ください。
3 Jenkinsへアクセスしてパスは、http[s]://<ホスト名>/jenkins/でしょうか?
4 また、ファイアウォールを無効にした上で、http://ホスト名:8080/jenkins/へはアクセスできるでしょうか?

よろしくお願いします。

**Comment by okahiro** [comment]
早速の返信ありがとうございます。

１．初期ユーザーadminでもダメでした。（初期パスワード、Redmine内で変更した後も同じでした）
２．Gitはコマンドでcloneしようとしてもパスワードを入力するとAuthentication failedとなり、ブラウザでのアクセス、SourceTreeというソフトを使ってもだめでした。
　　ユーザーとパスワードを入力するダイアログが表示され、正しい情報を入力しても再度表示されて先に進みません。
　　URLはhttps://<ホスト名>/git/<プロジェクト名>
　　でアクセスしています。
３．Jenkinsへのアクセスは、https://<ホスト名>/jenkins
　　です。
４．http://ホスト名:8080/jenkins/　はアクセスできました。ただ、ユーザー認証はありませんでした。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
もう少し確認させてください。

■Gitについて
ユーザをプロジェクトに開発者、もしくは管理者として追加していますか?

■Jenkinsについて
Firewallを無効にするとどうなるんでしょうか。それでもダメな場合は、/var/log/httpdのログに何か書かれていませんか?

よおｒしくおねがいします。

**Comment by okahiro** [comment]
・Gitについて
　ご指摘のとおり、プロジェクトメンバーに設定がありませんでした。
　追加したところ、アクセスできました。大変失礼いたしました。

・Jenkinsについて
　/var/log/httpdのssl_error_logを見たところ、下記のようなエラーが出ていました。
[Sat Jan 26 09:22:04 2013] [error] [client XXX.XXX.XX.XX] AuthUserFile not specified in the configuration
[Sat Jan 26 09:22:04 2013] [error] [client XXX.XXX.XX.XX] mysql invalid encryption method sha1-rm

　FirewallはAWSのSecurityGroupで全Port許可にしても同じでした。

よろしくお願いいたします。

**Comment by mikoto20000** [comment]
> [Sat Jan 26 09:22:04 2013] [error] [client XXX.XXX.XX.XX] mysql invalid encryption method sha1-rm

ApacheのMySQL認証モジュールがsha1-rm形式に対応していないとエラーを出していますね。CentOSのデフォルトのapacheのmysql認証モジュールはsha1-rmに対応していないのでinst-script/rhel6フォルダにmod_auth_mysql.xxx.rpmというファイルをモジュールとしておいています。本来ならインストール時にインストールされるのですが、試しにrpm -Uvhで上記rpmをインストール後、

  $ /etc/init/d/httpd restart

でapacheをリスタートしてみて頂けますか?

**Comment by okahiro** [comment]
mod_auth_mysql-3.0.0-11.el6.1.redmine.x86_64.rpmをインストールしたらJenkinsにログインできるようになりました！
ありがとうございます！！

パッケージの依存関係などで少しひっかかったので、一応過程を。。

Alminiumインストール直後に"mysql -qa |grep mysql"コマンドを実行するとこうなっていました。

```
mysql55-5.5.29-1.27.amzn1.x86_64
mysql55-libs-5.5.29-1.27.amzn1.x86_64
mysql55-server-5.5.29-1.27.amzn1.x86_64
mysql55-devel-5.5.29-1.27.amzn1.x86_64
mysql-devel-5.5-1.3.amzn1.noarch
mysql-server-5.5-1.3.amzn1.noarch
mysql-5.5-1.3.amzn1.noarch
mysql55-common-5.5.29-1.27.amzn1.x86_64
mod_auth_mysql-3.0.0-18.10.amzn1.x86_64
```

mod_auth_mysql-3.0.0-11.el6.1.redmine.x86_64.rpmをインストールしようとするとlibmysqlclient.so.16の依存性で怒られるので、mysql51-libsをインストールし、その後--forceオプションをつけて強制インストールしました。

```
mysql55-5.5.29-1.27.amzn1.x86_64
mysql51-libs-5.1.66-1.57.amzn1.x86_64
mysql55-libs-5.5.29-1.27.amzn1.x86_64
mysql55-server-5.5.29-1.27.amzn1.x86_64
mysql55-devel-5.5.29-1.27.amzn1.x86_64
mysql-devel-5.5-1.3.amzn1.noarch
mysql-server-5.5-1.3.amzn1.noarch
mod_auth_mysql-3.0.0-11.el6.1.redmine.x86_64
mysql-5.5-1.3.amzn1.noarch
mysql55-common-5.5.29-1.27.amzn1.x86_64
```

Apacheを再起動したら、RedmineのユーザーでJenkinsにログインできるようになりました。
（admin、別ユーザーともにOK）

いろいろ教えていただきありがとうございました！
