### ISSUE TITLE
G-mail 465番ポートが使えない

### ISSUE THREAD

**Issue by angelndxp** [alminium/alminium#75]
Redmine で Gmail SMTP 465番ポートが使えないことがわかりました(バージョンが上がったせいという可能性もあります)。このままではインストーラー内のG-mail自動設定が使えません。

　このため、G-mailの自動設定ポートを587番ポートへ移行しようと思います。(587番ポートで動作確認しました)

　修正個所は、 config-email.sh の142行目 

誤) SMTPPORT=465
　↓
正) SMTPPORT=587

となります。

　簡単な修正なのですが、こちらからPullリクエストを出す必要はあるでしょうか？

[同じ症状が他でも出ている様子]
http://in.shappi.org/article/161327903.html

**Comment by mikoto20000** [comment]
Redmine公式のドキュメントでは587を使うようになっていますね。

http://www.redmine.org/projects/redmine/wiki/EmailConfiguration

修正しておきますが、なぜ今まで465に設定されていたのでしょうか。

**Comment by angelndxp** [comment]
以前のバージョンとメール送信のデフォルト動作が変わったようです。
　これはrubyのメール送信機能の影響らしく、デフォルトの送信がTLS優先となったようです。
　その結果、Gmail設定でSSL優先のつもりで465番ポートに設定していたものが合わなくなった → TLS 587番ポートへ変更、となりました。
　一方、Windows Liveは、SSLもTLSもどちらも587番ポートで通じるので影響なしとなりました。

　修正ありがとうございます。

**Comment by mikoto20000** [comment]
ありがとうございます。

修正したのでクローズします。
