### ISSUE TITLE
リポジトリ情報が更新されない(Git)

### ISSUE THREAD

**Issue by adamario** [alminium/alminium#76]
以下のページを参考にしてRedmineで閲覧するためのbareレポジトリは作成し、
cloneした時点のレポジトリ情報は参照できるのですが、それ以降の更新が
されませんでした。
http://www.redmine.org/projects/redmine/wiki/JaRedmineRepositories

またpushをトリガーに以下のURLを実行してレポジトリ情報を更新しようと
しましたが、同じく更新はされませんでした。
http://＜ALminiumサーバー名＞/sys/fetch_changesets?key=＜apiキー＞

---

(上記URLを実行した際の/opt/alminium/log/production.log)
Started GET "/sys/fetch_changesets?key=＜apiキー＞" for 10.75.152.71 at 2013-01-31 14:39:26 +0900
Processing by SysController#fetch_changesets as HTML
  Parameters: {"key"=>"＜apiキー＞"}
  Rendered text template (0.0ms)
　Completed 200 OK in 130ms (Views: 0.7ms | ActiveRecord: 5.7ms)

---

また Redmine側のbareレポジトリにて以下のコマンドをRedmine実行ユーザ
アカウントで正しく実行でき、Redmineのリポジトリ情報が更新されることは確認しました。

$ git fetch && git reset --soft FETCH HEAD`'

手順もしくは設定で不足や誤り等ありましたらご教授よろしくお願いします。

**Comment by mikoto20000** [comment]
基本的にALMiniumはGitのリポジトリを自動で設定してくれます。
まずは、下記の記事を読んで試してみて頂けますか?

http://alminium.github.com/alminium/git.html

よろしくお願いいたします。

**Comment by adamario** [comment]
回答ありがとうございます。
ご提示頂いた記事を参照しましたが、今回私が試みたい内容とは異なりました。

記事の中ではALminiumで共有レポジトリを所有するという形態のようですが
私が試みているのはGitlab(Gitlite)で管理しているリモートレポジトリをマスタとして
そこから最新の情報をRedmineが取る方法を模索しています。
尚、ALminiumとGitlab(Gitlite)は別サーバで運用をしています。

１点、誤解していたのですがsys/fetch_changesetsのURLを実行するとRedmineのbareレポジトリを
fetch →　reset してくれるものだと思っていました。
正しくはRedmineのbareレポジトリにあるHEADとdbに登録しているHEADを比較して
dbの方が古かったら更新するという処理内容のように見えますがあっていますでしょうか。

整理しますとgitへプッシュしてからRedmineで表示されるまで以下のような
流れになると思います。
1. Gitlab(Gitlite)で管理しているリモートレポジトリへプッシュ
2. Redmineのbareレポジトリでfetch&reset
3. dbのHEADを更新

そこで2の実行を自動化するには、Gitlab(Gitlite)で管理しているリモートレポジトリのpost-recieveで
2の処理をキックするしか方法はないでしょうか。

ALminium側でsys/fetch_changesetsのようなURL実行で行える方法がありましたら
ご教授よろしくお願いします。

**Comment by mikoto20000** [comment]
他のGitリポジトリと組み合わせたことはないのですが、上記の2をやりたいのであれば、cronで定期的に同期させるとかではだめなのでしょうか?

**Comment by adamario** [comment]
返信遅くなりまして申し訳ありません。
cronでの実行、ご提案ありがとうございます。試してみたいと思います。

本件はクローズさせていただきます。ご対応ありがとうございました。
