### ISSUE TITLE
LDAP認証を使ったGit、Subversionの使用が不可能

### ISSUE THREAD

**Issue by dolphin2013** [alminium/alminium#78]
最近ALMiniumの存在を知り、導入のし易さに大変驚いている者です。

早速、CentOS6にALMiniumをインストールし、RedmineでLDAP認証ができるところまで設定し終えました。
ですが、LDAP認証されたIDでGitのclone/pushやSubversionのcheckout/commitができません。

ALMiniumのインストール後、LDAP認証あたりの設定は自力でする必要がありますでしょうか？

LDAP認証されたIDでGitやSubversionの利用ができたという方、もしくはわかる人がいましたらアドバイスを頂けると幸いです。

ちなみに、LDAP認証はWindowsServer2008R2のActiveDirectoryを使用しております。

以上、よろしくお願いいたします。

**Comment by dolphin2013** [comment]
自己解決しました。
行った設定は下記の通りです。

・モジュール Authen::Simple::LDAPをインストール
・/etc/httpd/conf.d/vcs.conf に下記の一行を追記
   PerlLoadModule Authen::Simple::LDAP

以上です。

**Comment by mikoto20000** [comment]
お役に立てなくてすみません。自己解決したようでよかったです。

今後ともよろしくお願いいたしますm(__)m
