### ISSUE TITLE
リポジトリへのコミット時にコミット情報が取得できない場合がある（修正コード付き）

### ISSUE THREAD

**Issue by ucho** [alminium/alminium#83]
複数リポジトリを扱っている場合など、リポジトリのディレクトリ名がプロジェクトの識別子と一致しない場合、コミット時のコミット情報取得に失敗するので、原因箇所を修正してみました。

https://gist.github.com/ucho/5211562

bin/alm-sync-scm を修正したものです。
パイプ後のsedの式を修正し、ディレクトリ名から「プロジェクトの識別子のはずの部分」を切り出すようにしました。
つまり、
/path/to/repos/proj.repo から proj の部分を切り出します。
/path/to/repos/repo のような場合は従来通り repo を切り出します。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

遅くなりましたが、頂いた修正案で修正させて頂きました。

今後ともよろしくお願いしますm(__)m
