### ISSUE TITLE
WikiのSyntaxヘルプがリンクになっていません

### ISSUE THREAD

**Issue by JudasSeven** [alminium/alminium#85]
## 環境

Ubuntu Server 12.04 LTSにalminiumをインストールしました。
alminiumのファイルをMasterブランチからDownloadしたのですが、alminiumのversionが不明です。
redmine 2.2.4 stableが入っています。
## 症状

複数行にまたがる入力欄（Wikiなど）の右肩に
/plugin_assets/redmine_redcarpet_formatter/help/wiki_syntax.html
という文字が表示されている状態になっています。
以前の状態では、インフォメーションアイコンとWikiのシンタックスについてのWindowがPopupするリンクが当該の位置にありました。

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。

Redmine Redcarpet FormatterプラグインをRedmine 2.3に対応させたときにRedmine 2.2で
崩れるようになってしまったようです。

/opt/alminium/plugins/redmine_redcarpet_formatter

ディレクトリで、

```
# git checkout ed2475ee
```

とし、Redmine2.3対応前のバージョンを利用することで解決できるかと思います。

よろしくお願いいたします。
