### ISSUE TITLE
mod_sslを削除したところ、接続できなくなりました

### ISSUE THREAD

**Issue by Meganezaru** [alminium/alminium#89]
ALMinium利用させていただこうと、設定中です。

Windowsに初めてRedmineをインストールしたときに、かなり時間がかかったのですが、ALMiniumは、何の苦労もなく立ち上がってしまって、驚きでした。

すばらしいものを提供していただき、ありがとうございます！

インストールしたまま利用していれば、問題なかったと思われますが・・・
SSLサポートでインストールしたところ、あの真っ赤な画面がどうしても気になってしまったので、SSLを外すことにしました。

FAQにあったように、mod_sslを削除（sudo yum remove mod_ssl）し、httpdを再起動（sudo /etc/rc.d/init.d/httpd restart）をしたところ、同様にhttpsとして認識され、接続できません。

試しにredmine.confも修正し、httpdを再起動するも、現象かわらず・・・

ここで、RewriteEngineの値をOnに戻し、パターンをhttpsからhttpに変更して試してみましたが、今度は、リダイレクトループとやらになりました・・・笑

うすうすお気づきだとは思いますが、私、Linux系は全くの初心者でして・・・Google先生の言うがままに操作をするぐらいしかできないため、きっと初歩的な何かが抜け落ちてるのだと思います。

いろいろ調べてみましたが、今のところ解決策が見えず・・・よろしければ助言いただけるとありがたいです。

Issueの利用方法とは、ずれているとは思いますが・・・よろしくおねがいします。

サーバー環境は、さくらVPSのCentOS6です。

**Comment by Meganezaru** [comment]
すいません・・・

理由は分かりませんが、解決しました。

post_installのスクリプトを眺めてみたら、最後にhttpdの起動方法が載っていたので、その方法で立ち上げ直してみただけです。

SSLが無効になるのに、多少時間がかかるとか、環境上の問題だったんでしょうか？

いずれにせよ、お騒がせしました・・・
申し訳ありませんでした。

**Comment by mikoto20000** [comment]
お返事がおそくなりすみません。

httpdを再起動しないとhttpd.confの設定が再読み込みされないからです。mod_sslパッケージを削除しただけではhttpsへのリダイレクトが止まらないのは、単にブラウザがキャッシュしていただけかもしれません。

**Comment by Meganezaru** [comment]
いえいえ、ご返事ありがとうございました！

とりあえず、httpdの再起動方法は覚えましたので、今後は大丈夫だと思います。

ただいま、悪戦苦闘しています・・・(笑)
勉強のためにも、極力自力で解決しようとおもってますが、どうにもならないときは、質問させていただくかもしれません。

その際は、お暇なときでよいので、ご助言いただけるとありがたいです。

よろしくおねがいします。
