### ISSUE TITLE
[Ruby 2.0.0p195のサポート]修正漏れ

### ISSUE THREAD

**Issue by yukilabo** [alminium/alminium#91]
MINORVER=`grep "%define rubyminorver" ruby-2.0.spec | awk '{print $3}'`
の ruby-2.0.spec を ruby200.spec に変更する必要があります。

**Comment by yukilabo** [comment]
inst-script/rhel6/ruby2.0-install
  rpmbuild -bb ruby-2.0.spec
もruby200.specに変更する必要があります。

**Comment by mikoto20000** [comment]
すいません。修正漏れてました。

まだテストしていないのですが、masterブランチを修正したので、もしよろしければお試しください。

**Comment by yukilabo** [comment]
Serversman@VPSにてインストールしてみたところ、ALMiniumの画面が表示されました。
ありがとうございます。
