### ISSUE TITLE
/ruby-2.0.0-.tar.gzが存在しない模様

### ISSUE THREAD

**Issue by komarisu** [alminium/alminium#92]
Windows7にVMPlayerを入れて、CentOS6.4(Final)を新規にクリーンインストール。
Software Updateを当てる。
rootでalminiumのインストールを開始する。
http://ftp.ruby-lang.org/pub/ruby/ruby-2.0.0-.tar.gz
が404 not found
rakeなどのコマンドが存在しない。command not found
passenger等がエラーになっている。エラーでapacheが起動しない。
最新版をインストールする時に気を付けること等あるでしょうか？
シェルのruby-2.0.0-.tar.gzをruby-2.0-stable.tar.gzに書き換えれば
うまく行きそうな気もしてきたけど、作者のお墨付きが欲しい。

**Comment by tcmaru** [comment]
偶然にも、私も一昨日から似たような状況にハマっています。
VMware ESXi 5 の仮想マシンにCentOS 6.4_minimul_x64(Final)をインスト。
yumで全てアップデート。
インストーラー最終局面のapache起動時にエラーとなります。

inst-script/rhel6/httpd-redmine.conf　の冒頭に記述している、

LoadModule passenger_module /usr/lib64/ruby/gems/2.0.0/gems/passenger-%PASSENGER_VERSION%/libout/apache2/mod_passenger.so

がエラーを吐いていて、passengerモジュールが読み込めないと言われます。
loadできない原因は、komarisuさんが言うように、ruby2.0.0がlib64ディレクトリにインストール出来ていないせいですよね。

alminium.gitをcloneした後に、alminiumをcheckoutするとhttpd-redmine.confの中身がruby 1.9.1版になりますが、それでもhttpd起動エラーは回避できませんでした。

現時点でalminiumの最新版をインストールしようとすると、
Rubyは2.0
Passengerは4.0.2
という両者の最新版がインストールされるという前提でいけば、
httpd-redmine.confのpassenger moduleの記述は
lib64 を lib に置き換えなくても問題がないか、
apache2ディレクトリの一つ上のディレクトリ名は ext ではなくて libout で問題ないか、
も気になっています。

**Comment by tcmaru** [comment]
> mikoto20000さん
> komarisuさん

すみません、GitHub初心者なので「Issue」欄に書くことしかできず、ひとまず気づいた点を書かせていただきます。

今回、komarisuさんも私も、CentOSでした。
従って、rubyのrpmを取得するためのスクリプトを直せば良いのは、komarisuさんが気付いたとおりで
inst-script/rhel6/ruby2.0-install
の
echo "download error. 'ruby-2.0.spec'"
MINORVER=`grep "%define rubyminorver" ruby-2.0.spec | awk '{print $3}'
rpmbuild -bb ruby-2.0.spec
を修正すればOKです。

mikoto20000さんが対応していただいたruby2.0.0をwgetしてくる先がhansodeのruby200.specになっていたので、
ruby-2.0.spec => ruby200.specにすればOKでしょうか。

取り急ぎご報告でした。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

Ruby2.0.0がビルドできない不具合でした。修正したのでよろしければ
ご確認ください。

**Comment by mikoto20000** [comment]
tcmaruさん

ご指摘の通りです。ご報告ありがとうございました。

**Comment by komarisu** [comment]
修正版確認しました。
お忙しいところ、対応頂きありがとうございました。
