### ISSUE TITLE
Ruby2.0.0対応版での動作確認

### ISSUE THREAD

**Issue by momibun926** [alminium/alminium#94]
Ruby2.0.0対応版をインストールして、さらっと触ってみました。
・チャートの表示
・エクセルのエクスポートができませんでした
取り急ぎ、確認できた事象の報告です。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。お返事が遅くなってごめんなさい。

調べてみたところ、ALMiniumの最新版ではRedmine2.3を採用していますが、
Redmineバージョンアップに伴うプラグインの互換性がなくなったためと思われます。
下記のバージョンで修正されているようなので、よろしければお試しいただけますか?

redmine_xls_export
https://github.com/two-pack/redmine_xls_export/

のfeaturesブランチ(masterブランチではないので注意)

redmine_charts
https://github.com/drakontia/redmine_charts/

のmasterブランチ

動作確認をレポート頂ければ、上記のバージョンをALMiniumで利用するように修正したいと思います。

よろしくお願いします。

**Comment by momibun926** [comment]
レスポンスありがとうございます。

上記のバージョンで試してみましたところ、問題なく動きました。
ありがとうございます！

**Comment by momibun926** [comment]
最新版のインストールで、問題なく動作しました！
ありがとうございます。
