### ISSUE TITLE
Parallels上のubuntu12.04LTSでのインストールトラブル

### ISSUE THREAD

**Issue by sakaba37** [alminium/alminium#97]
マシン：MacBook Air（Mac OS X Lion 10.7.5）
OS：Parallels 7 提供のubuntu12.04LTS（64ビット版）
環境：Japanese team日本語設定/キーレイアウト変更/ホスト名設定

上記にインストールしたところ、２点トラブルがありました。
1. curlがないのでインストール中にエラー
   （inst-script/debian/jenkins-install: 行 45: curl: コマンドが見つかりません
   　inst-script/debian/jenkins-install: 行 54: curl: コマンドが見つかりません
   　proxy setting for jenkins fail）
   ＝＞上記環境再構築後に apt-get install curl で回避

2.mod_rewriteのエラー（１でやり直した後です）
（Syntax error on line 10 of /etc/apache2/sites-enables/jenkins
　Invalid command 'RewriteEngine', perhaps misspelled or ・・・）
＝＞ apache起動エラーでインストール中断後に
　http://ms2.seesaa.net/article/168747804.htmlの手順で、
　モジュールのないことを確認。a2enmod rewriteで有効にし、
　service apache2 restartしました。

なお、以下も出てましたが、トラブルではないと認識しています。
Could not reliably determine the server's fully qualified domain name

以上、簡単ですが、ご報告いたします。

最後になりましたが、素晴らしい環境をありがとうございます！

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。修正しました。
