### ISSUE TITLE
チケット作成時に、進捗率のカラムが無い

### ISSUE THREAD

**Issue by yamaguchie** [alminium/alminium#98]
チケット作成時に、進捗率の項目が無い。
私の設定が悪いかもしれません。
わかる範囲で教えてください。

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。

ALMiniumでは、デフォルトでは、チケットのステータスから進捗率を自動的に計算するようになっています。
進捗率を手入力したい場合は、

「管理」＞「設定」＞「チケットトラッキング」＞「進捗の算出方法」

から設定を変更してください。よろしくお願いいたします。
