### ISSUE TITLE
passengerの設定でエラー

### ISSUE THREAD

**Issue by yamaguchie** [alminium/alminium#99]
- 環境
  - CentOS６系
- 事象
  シェルの最後で以下のメッセージ。

httpd を停止中:                                            [  OK  ]
httpd を起動中: httpd: Syntax error on line 221 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.d/redmine.conf: Cannot load /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.8/libout/apache2/mod_passenger.so into server: /usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.8/libout/apache2/mod_passenger.so: cannot open shared object file: No such file or directory
                                                           [失敗]
- 対応
  - /etc/httpd/conf.d/redmine.confを修正

*　修正後のパス

/usr/lib64/ruby/gems/2.0.0/gems/passenger-4.0.8/buildout/apache2/mod_passenger.so

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

Passenger4.0.8からパスが変わったのですね。(以前も勝手に変えられて動かなくなりました＞＜)
頂いた点は修正したので、最新版は動作すると思います。
